{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Indice\",\"CAmoyMed\",\"VSTERILISATION\",\"BlocsJ\",\"ExterneDetails\",\"Bloc_H\",\"Vtendance\",\"VTracabilité\",\"VCa_Realisé\",\"Vhospitalisé\",\"VPatient\",\"Vurgence\",\"VHopitalJour\",\"VDetails_CA_Facture\",\"Vtop5_Dep\",\"Vconsommation_M\",\"VCompta\",\"VMasse_Salariale_CA\",\"Alertes\",\"Requête1\",\"VDettes\",\"VFacturation\",\"V_Marge\",\"reporting PEC_Expedition\",\"VhospitaliseJour\",\"v_occupation_bloc\",\"Mesure_BlockHeure\",\"BlocsHeure\",\"VRecouvrement\",\"VHopital_Jour\",\"Mesure Achat_Stock\",\"V_achat_Stock\",\"Reporting Prestation_annule\",\"Reporting Suppression_avance\",\"Reporting Admission_annuler\",\"Reporting Dossier_Payant_cloturer_Non_Paye\",\"reporting effectif\",\"reporting cotisation\",\"reporting salaire\",\"reporting heure_supp\",\"reporting prime\",\"ClFacture\",\"Mesure\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "fc91ebbe-474e-4a63-addb-4deb3bfb36ec",
        "fromColumn": "DateM",
        "fromTable": "CAmoyMed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_eb4f5786-33a7-4f29-913a-84cd598cc2a0"
      },
      {
        "name": "616cfa7b-6574-4c14-8105-45865fdb6884",
        "fromColumn": "DatArr",
        "fromTable": "ExterneDetails",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a51c7a4b-f256-47be-a62f-1151859bf39c"
      },
      {
        "name": "8fea01ec-6a72-4a63-b70c-aa94d787847d",
        "fromColumn": "DateD",
        "fromTable": "Bloc_H",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b50ce89e-43cd-4a77-b611-c18a5385677a"
      },
      {
        "name": "8b7a8b41-cdbf-4bf2-b761-8f1b943488ee",
        "fromColumn": "DatOpe",
        "fromTable": "VCa_Realisé",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dae2407d-90ea-45ff-bbe1-34a10c573343"
      },
      {
        "name": "1b3e999e-4850-4d23-b9ac-377b5e1fbb77",
        "fromColumn": "Column1",
        "fromTable": "Requête1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_02ff1113-7a7e-4474-bba1-bdccd862917e"
      },
      {
        "name": "a796c01d-64dd-4f6f-aefa-9f40e8db2619",
        "fromColumn": "DatFac",
        "fromTable": "reporting PEC_Expedition",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2184aada-f849-4f69-9b2e-3face548d3fd"
      },
      {
        "name": "0b92570b-fda3-444a-9953-76f72691d596",
        "fromColumn": "mois",
        "fromTable": "VTracabilité",
        "toColumn": "mois",
        "toTable": "Vconsommation_M"
      },
      {
        "name": "f761c637-de3e-41e2-ace7-0fc1e0862b12",
        "fromColumn": "DatFac",
        "fromTable": "recouvrement",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bca547ae-0462-46ef-b15b-d3fdd8c08999"
      },
      {
        "name": "2ab5b14b-a4dc-4dc0-9975-311f952177ff",
        "fromColumn": "DatArr",
        "fromTable": "Vurgence",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_69ee96d6-e8f8-4333-a0f0-ef23fbc1a166"
      },
      {
        "name": "d282e541-fd49-476d-953c-0e0a19df3aef",
        "fromColumn": "DatEnvoi",
        "fromTable": "reporting PEC_Expedition",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5a44dc05-5a38-44b2-943f-380f666a1aca"
      },
      {
        "name": "AutoDetected_af479b77-c2cf-4a86-9803-8bce270fa2cb",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "jour",
        "fromTable": "VHopitalJour",
        "toColumn": "jour",
        "toTable": "Vhospitalisé"
      },
      {
        "name": "c6e4bf07-8d03-4cb0-9f5d-cc01748a3853",
        "fromColumn": "Date_Reservation",
        "fromTable": "BlocsHeure",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_17f3f2ef-7b30-43f3-bce4-4fa188a4e931"
      },
      {
        "name": "2c898ca9-61ba-4c9b-8811-adf63950cdde",
        "fromColumn": "Date suppression",
        "fromTable": "Reporting Prestation_annule",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a60faa9b-c25c-40e4-af40-a8c6cf54653f"
      },
      {
        "name": "b753c6cd-45ab-4c3e-85e0-3db4d09c664b",
        "fromColumn": "Date prestation",
        "fromTable": "Reporting Prestation_annule",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_08212afe-ece0-4abe-8e80-9e00b104b9f5"
      },
      {
        "name": "7fdd00ef-a1a9-42bc-a868-df945c82cafa",
        "fromColumn": "Heure prestation",
        "fromTable": "Reporting Prestation_annule",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9e05e250-3c67-4c7c-b0bb-041150b40c55"
      },
      {
        "name": "4f59169f-6cb1-447f-88d6-5088ca6e5e93",
        "fromColumn": "Date Avance",
        "fromTable": "Reporting Suppression_avance",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e65b8459-4980-4481-820c-ba77f6edd273"
      },
      {
        "name": "85843a0e-3a10-4736-9266-a0fb47a0b763",
        "fromColumn": "Heure Avance",
        "fromTable": "Reporting Suppression_avance",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a11b5d35-863d-4f32-b536-99d7a77439cf"
      },
      {
        "name": "cdfda844-6517-4826-aec7-2c94d0ef61b6",
        "fromColumn": "Date suppression",
        "fromTable": "Reporting Suppression_avance",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b2cdc53a-8505-4a33-a7ba-ac24c0adf7ac"
      },
      {
        "name": "b213606c-2c04-406b-af5a-a013108cfeb9",
        "fromColumn": "Date arrivée",
        "fromTable": "Reporting Admission_annuler",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9e203b7e-eb75-4bbe-9976-3e192f389d3a"
      },
      {
        "name": "9ee58c0d-44c0-4c51-b9de-f03822faa229",
        "fromColumn": "Date annulation",
        "fromTable": "Reporting Admission_annuler",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e2992f1c-fbda-4596-aaed-0ff256aac785"
      },
      {
        "name": "a8f6619e-3d33-4f79-815c-b216715aaa2c",
        "fromColumn": "Date arrivée",
        "fromTable": "Reporting Dossier_Payant_cloturer_Non_Paye",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8aac830b-72ff-43c3-a415-5051460e140c"
      },
      {
        "name": "0bbd8ef4-412d-47f4-ac7b-e86ec678cafa",
        "fromColumn": "dat",
        "fromTable": "reporting heure_supp",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_137e3c2f-f97a-4860-8e0d-8a8bad887304"
      },
      {
        "name": "97b47a86-5498-4806-841b-8b24dfd8fee4",
        "fromColumn": "date",
        "fromTable": "reporting prime",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_22e0cf24-75e7-40be-9ccf-5d86ebdca70a"
      },
      {
        "name": "09b34272-7f48-840a-7530-710de200f9f7",
        "fromColumn": "moisannee",
        "fromTable": "reporting effectif",
        "toCardinality": "many",
        "toColumn": "mois annee",
        "toTable": "Dates"
      },
      {
        "name": "561e007e-ea1c-4b64-adc3-e3e0092e4b21",
        "fromColumn": "HeuOpe",
        "fromTable": "ClFacture",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6dbfa5a2-7d5e-4d69-b347-8b79a80803d3"
      },
      {
        "name": "5b256c9a-070b-4971-bab3-1ab5dde0bd8d",
        "fromColumn": "DatFac",
        "fromTable": "ClFacture",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c5b42fc4-4d63-4130-85dc-64b9426da457"
      },
      {
        "name": "fd28d40c-e0a9-45fc-be0b-13b6fc892bfc",
        "fromColumn": "Datdel",
        "fromTable": "ClFacture",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dc08e2f9-2e5d-4293-aebb-3f213209a326"
      },
      {
        "name": "5ec29747-c6e7-46e5-8f31-fa2d24f1289b",
        "fromColumn": "Date_Remise",
        "fromTable": "ClFacture",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e2f21bfc-d774-4e2b-84d2-cd41e8fad56f"
      },
      {
        "name": "b8fb393b-98af-4654-9120-0c78f81074eb",
        "fromColumn": "date_valider_ho",
        "fromTable": "ClFacture",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e39e7027-7cab-4869-99f4-0ec0692a857b"
      },
      {
        "name": "6318917f-5357-45ca-bf3f-b83946fd7282",
        "fromColumn": "Date",
        "fromTable": "Dates",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9a7f01e8-a7fa-4689-91b2-feb5608b4ba7"
      },
      {
        "name": "2e1d3a8d-6b73-ea4e-4ced-34f3d69e06bf",
        "fromColumn": "date",
        "fromTable": "reporting salaire",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "3fcce6fb-386c-3d75-b3f4-eb318cd51a9b",
        "fromColumn": "DatOpe",
        "fromTable": "ClFacture",
        "toColumn": "Date",
        "toTable": "Dates"
      },
      {
        "name": "f9a074a9-e4ba-1aa7-01e2-2d84c54ada60",
        "fromColumn": "Dat",
        "fromTable": "reporting cotisation",
        "toColumn": "Date",
        "toTable": "Dates"
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "Indice",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "DESIGNATION",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "585f7b51-9602-4499-9538-9633eea76dca",
            "sourceColumn": "DESIGNATION",
            "sourceProviderType": "varchar(22)",
            "summarizeBy": "none"
          },
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b4b4dbc9-8c1d-429d-923c-65016ce24eb3",
            "sourceColumn": "Indice",
            "sourceProviderType": "decimal(38, 3)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "05fde8cf-55d5-4c5f-9dd1-dc248bba85b4",
        "measures": [
          {
            "name": "CA Facturé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"Ca Facturé\")",
            "formatString": "#,0",
            "lineageTag": "eaabaeff-f296-4e90-91e2-7beb75e37115"
          },
          {
            "name": "CA Realisé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CA Realisé\")",
            "formatString": "0",
            "lineageTag": "f4228d46-81f0-4921-baec-2057c1859a29"
          },
          {
            "name": "Nbr Urgence",
            "displayFolder": "Nombre",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"nbr urgence\") & \"/ \" & Round(CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CA_urgence\"),0) & \" MAD\"",
            "lineageTag": "c6241791-6a93-4b07-ad32-428ade59e13f"
          },
          {
            "name": "Nombre hospitalisé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Nombre",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"Nombre hospitalisé\")",
            "formatString": "0",
            "lineageTag": "baa74437-3197-4ed8-b96e-ab83aca31f3b"
          },
          {
            "name": "Nombre Hopital du jour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Nombre",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"Nombre Hopital du jour\")",
            "formatString": "0",
            "lineageTag": "6e246125-7ef1-4060-a56b-8f9edce41530"
          },
          {
            "name": "Nombre Patient Externe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Nombre",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"Nombre Patient Externe\")",
            "formatString": "0",
            "lineageTag": "2b909026-f493-4a3e-b77a-da359a796076"
          },
          {
            "name": "Nombre de lits occupé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Nombre",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"Nombre de lits occupé\")",
            "formatString": "#,0",
            "lineageTag": "5243d953-0642-4a87-bcd7-518b8acc591f"
          },
          {
            "name": "CJ espece",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CJ espece\")",
            "lineageTag": "ffc0f4f7-297f-4a62-89a9-9f7955e8dbda"
          },
          {
            "name": "CJ cheque",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CJ cheque\")",
            "lineageTag": "2a148070-3031-40a1-840a-38040f4edf53"
          },
          {
            "name": "CJ traite",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CJ traite\")",
            "lineageTag": "db9a9f6f-97db-427a-8526-8909740a0e0f"
          },
          {
            "name": "CJ TPE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CJ TPE\")",
            "lineageTag": "5c8e9193-7c76-45f3-9b22-572d81c28ea2"
          },
          {
            "name": "Caisse",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),FILTER(Indice,CONTAINSSTRING(Indice[DESIGNATION],\"CJ\")))",
            "formatString": "0",
            "lineageTag": "9d072dff-bc13-4f1c-9328-33b1af1c60db"
          },
          {
            "name": "CR Virement",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CR Virement\")",
            "lineageTag": "353ec214-ca77-4b4a-b4fd-60d3f823d7fd"
          },
          {
            "name": "CR Traite a terme",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CR Traite a terme\")",
            "lineageTag": "895dea2a-f861-4b57-869f-44878b30085c"
          },
          {
            "name": "CR Traite echues",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CR Traite echues\")",
            "lineageTag": "eece1c1d-8e6f-451c-bf57-b0c9b0665afa"
          },
          {
            "name": "CR cheque a terme",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CR cheque a terme\")",
            "lineageTag": "b879fef0-8b9c-4fd8-97b7-8d049b771d3d"
          },
          {
            "name": "CR cheque echues",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CR cheque echues\")",
            "lineageTag": "e21fd54a-d6b0-4582-a352-1fd31465b7e1"
          },
          {
            "name": "CR espece",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CR espece\")",
            "lineageTag": "d063e2f8-a0c6-4147-a3e4-70b8cd7e1f74"
          },
          {
            "name": "Solde Trésorerie",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),FILTER(Indice,CONTAINSSTRING(Indice[DESIGNATION],\"CR\")))",
            "formatString": "#,0",
            "lineageTag": "48a9e0cd-4d08-4265-81f8-e61d04cb82f6"
          },
          {
            "name": "Ajustement Moyen",
            "expression": "CALCULATE(SUM(Indice[Indice]),FILTER(Indice,Indice[DESIGNATION]=\"ajustement moyen\"))",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "b480b320-c751-4e6b-a5fa-4dc1bb60f370"
          },
          {
            "name": "remise moyenne",
            "expression": "CALCULATE(SUM(Indice[Indice]),FILTER(Indice,Indice[DESIGNATION]=\"remise moyenne\"))",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "84af3563-0e28-4be1-8deb-b59c78ee18c3"
          },
          {
            "name": "marge pharmacie",
            "expression": "CALCULATE(SUM(Indice[Indice]),FILTER(Indice,Indice[DESIGNATION]=\"marge pharmacie\"))",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "87fea47c-f530-4321-88dc-1fa382dddb69"
          },
          {
            "name": "CA_Urgence",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE(SUM(Indice[Indice]),FILTER(Indice,Indice[DESIGNATION]=\"CA_urgence\"))",
            "lineageTag": "822b29db-0d7c-43e7-98fd-8588814edb59"
          },
          {
            "name": "Masse Salariale / CA",
            "expression": [
              "VAR A=CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"Masse Salariale / CA\")",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "c0444735-5556-4755-b821-90362da97969"
          },
          {
            "name": "KOperatoire",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"KOperatoire\")",
            "formatString": "0",
            "lineageTag": "32d69a50-2291-4121-b1b7-276398183b79"
          },
          {
            "name": "CAMoyenChambre",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Indice[Indice]),Indice[DESIGNATION]=\"CAMoyenChambre\")",
            "formatString": "0",
            "lineageTag": "e86f2f02-733f-442c-b9c7-dec412123735"
          }
        ],
        "partitions": [
          {
            "name": "Indice",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Indice = Source{[Schema=\"dbo\",Item=\"Indice\"]}[Data]",
                "in",
                "    dbo_Indice"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_adfd319a-0a8b-4659-a30b-a37e9eeb4d17",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ccaa5b76-88db-4f8c-8de2-ab577eebf69c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "53c12ab1-6122-4361-9bab-aeb4bc527c78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3ddb82f3-ed91-4396-96ca-acf1193f12ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4a9f171a-8e3b-4f24-bad8-6d2c5ba7ce26",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "69de2991-7fd7-4f6a-8eb6-f3d418d75abf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "63451f91-831a-4e78-b478-e21c77776a4c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b1630770-8500-4d37-8196-1cfd387e1e0c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0b110754-3bf0-486a-a8e6-2e0097cb5695",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "beed9675-dd7c-4209-890c-7ac2b290e9b3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d9137b1d-6f67-4cac-b5d2-47d58867670f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "81a9adc2-cf9c-41af-a450-5bd7d0a90156",
                "ordinal": 3
              }
            ],
            "lineageTag": "3b5b5251-89cb-40a2-b0f8-0b798e9bed2f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "abd079c3-d5f1-454b-bea6-374fd25d2a1c",
        "partitions": [
          {
            "name": "DateTableTemplate_adfd319a-0a8b-4659-a30b-a37e9eeb4d17",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "CAmoyMed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "codmed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae7da9ad-e908-4566-8570-b5bd4ed366c2",
            "sourceColumn": "codmed",
            "summarizeBy": "none"
          },
          {
            "name": "nommed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd448435-4e14-4e4a-bea0-28a0658139ef",
            "sourceColumn": "nommed",
            "summarizeBy": "none"
          },
          {
            "name": "DateM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "9b40cd32-7fcf-4aaf-a8c2-49eb2867cbdc",
            "sourceColumn": "DateM",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_eb4f5786-33a7-4f29-913a-84cd598cc2a0"
                },
                "isDefault": true,
                "relationship": "fc91ebbe-474e-4a63-addb-4deb3bfb36ec"
              }
            ]
          },
          {
            "name": "AVG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a0c25306-1080-4742-920b-32dbbc6847f2",
            "sourceColumn": "AVG",
            "summarizeBy": "sum"
          },
          {
            "name": "nb_admission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "006cab95-ab62-4126-9b8c-f88ec3c709e4",
            "sourceColumn": "nb_admission",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4b75ca88-cda1-4374-9e51-108806972d75",
        "measures": [
          {
            "name": "Avreage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "sum(CAmoyMed[AVG])",
            "formatString": "#,0",
            "lineageTag": "a982e547-6201-4a10-a8f4-66b03a3a34ba"
          },
          {
            "name": "Nombre admission",
            "expression": "sum(CAmoyMed[nb_admission])",
            "formatString": "0",
            "lineageTag": "f503db03-42d7-4b22-8712-8566c366747d"
          }
        ],
        "partitions": [
          {
            "name": "CAmoyMed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_CAmoyMed = Source{[Schema=\"dbo\",Item=\"CAmoyMed\"]}[Data]",
                "in",
                "    dbo_CAmoyMed"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_eb4f5786-33a7-4f29-913a-84cd598cc2a0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2ea90c0c-778c-459a-84ae-98fe7952643f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9150d2d1-e7c0-452b-98e2-7730f0784c49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "48c6ae69-c7e7-4afd-bb91-001ba37f697c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4bf17646-6b99-4dbc-ac95-a5ea43fff1e9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3e20bd6b-40c0-4eb7-8968-51137e85c909",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0bb6829d-d95a-491f-b53b-afc1eebfbb4f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "446b416b-3842-44b0-bf23-a61f97b3df42",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ba11e371-ca95-4d6d-b025-5137568e192b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6e45b834-1e61-4750-a168-2249b6014787",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "abe0051a-f9f9-4a6c-b5a7-5dc0b0b56238",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e84222ff-8580-4dbb-ad04-26498fe4e875",
                "ordinal": 3
              }
            ],
            "lineageTag": "53214c3e-6c9e-4004-8d8b-be201a7e483d"
          }
        ],
        "isHidden": true,
        "lineageTag": "750a001d-ebbb-49ec-9244-32e6e9c0f130",
        "partitions": [
          {
            "name": "LocalDateTable_eb4f5786-33a7-4f29-913a-84cd598cc2a0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('CAmoyMed'[DateM])), 1, 1), Date(Year(MAX('CAmoyMed'[DateM])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "BlocsJ",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c39d130e-9b6d-4202-8d6f-895b6f51cd42",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5748b48f-806b-4c1c-bf57-c2c08fb62622",
            "sourceColumn": "annee",
            "summarizeBy": "sum"
          },
          {
            "name": "mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b2b034c-3a2a-481b-8688-015118a07f2b",
            "sourceColumn": "mois",
            "summarizeBy": "sum"
          },
          {
            "name": "realiser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5bb793ff-1c84-4129-80f3-d04cf6054c52",
            "sourceColumn": "realiser",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2893d549-697e-40d6-92b4-8c59dcabeccc",
        "measures": [
          {
            "name": "realiseé",
            "expression": "SUM(BlocsJ[realiser])",
            "formatString": "0",
            "lineageTag": "6c6cef7b-d1c8-4e98-b46f-3b65aad04f4c"
          }
        ],
        "partitions": [
          {
            "name": "BlocsJ",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_BlocsJ = Source{[Schema=\"dbo\",Item=\"BlocsJ\"]}[Data]",
                "in",
                "    dbo_BlocsJ"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ExterneDetails",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "LibNat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "762c9386-38b4-47a3-ba5c-9e540e86eef9",
            "sourceColumn": "LibNat",
            "summarizeBy": "none"
          },
          {
            "name": "Designation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3f3e44a-339f-43f1-b954-09385585e011",
            "sourceColumn": "Designation",
            "summarizeBy": "none"
          },
          {
            "name": "Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f6b352d-0a38-4f5e-b4c1-c4782b447b09",
            "sourceColumn": "Nbr",
            "summarizeBy": "sum"
          },
          {
            "name": "CA_realisé",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d28700e5-8c5a-4f72-a94a-e011bf32e500",
            "sourceColumn": "CA_realisé",
            "summarizeBy": "sum"
          },
          {
            "name": "DatArr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9f0b8100-f858-472d-8719-9f3141ea95e1",
            "sourceColumn": "DatArr",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a51c7a4b-f256-47be-a62f-1151859bf39c"
                },
                "isDefault": true,
                "relationship": "616cfa7b-6574-4c14-8105-45865fdb6884"
              }
            ]
          },
          {
            "name": "Nombre de Semaines par Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKNUM(ExterneDetails[DatArr])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b24cc1e2-4cb4-4e40-90cf-2d541ca2d29b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "FORMAT(",
              "    'ExterneDetails'[DatArr],",
              "    \"dddd\",\"fr-FR\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f3f57382-9d56-4db8-adfb-fb40815f7af1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "506fbcd8-26e6-420f-a1e5-4ba32ec862c5",
        "measures": [
          {
            "name": "Couunt",
            "expression": "sum(ExterneDetails[Nbr])",
            "formatString": "0",
            "lineageTag": "260b8032-b6b3-4108-833c-975d0b1fb30d"
          },
          {
            "name": "CA_Realisée",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM((ExterneDetails[CA_realisé]))",
            "lineageTag": "aa52ee83-586c-4929-969f-d98303059135"
          },
          {
            "name": "externeJ",
            "expression": "CALCULATE(sum(ExterneDetails[Nbr]),FILTER(ExterneDetails,ExterneDetails[DatArr]=TODAY()))",
            "formatString": "0",
            "lineageTag": "5c36dab5-234c-4c60-a79c-493ddb888b13"
          },
          {
            "name": "nbr admiss/semaine",
            "expression": [
              "VAR LastDay = CALCULATE(Max('ExterneDetails'[Nombre de Semaines par Mois]), ALL('ExterneDetails'))",
              "RETURN",
              "    CALCULATE(",
              "        [Couunt],",
              "        'ExterneDetails'[Nombre de Semaines par Mois] = LastDay",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "2bca8d82-fe71-41bf-8854-9aca5f3bc65b"
          },
          {
            "name": "réalisé/semaine",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR LastDay = CALCULATE(Max('ExterneDetails'[Nombre de Semaines par Mois]), ALL('ExterneDetails'))",
              "RETURN",
              "    CALCULATE(",
              "        [CA_Realisée],",
              "        'ExterneDetails'[Nombre de Semaines par Mois] = LastDay",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "3e1014d6-c89c-45a8-bdc6-ba730a61d0d6"
          }
        ],
        "partitions": [
          {
            "name": "ExterneDetails",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_ExterneDetails = Source{[Schema=\"dbo\",Item=\"ExterneDetails\"]}[Data]",
                "in",
                "    dbo_ExterneDetails"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a51c7a4b-f256-47be-a62f-1151859bf39c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b3efe971-5a9d-4b97-90ed-71ac55da0cb1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "38fc79da-3e00-466f-92be-2d857fd819e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "dd1b1254-8a15-4268-9185-1ab314778b34",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "653395ed-affb-4ded-87ce-e80cc07a16d7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e80e045e-e62d-45a8-9cc3-d2aa335dfaa5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "98a47337-6211-4b1d-ac0b-b5be7e59d591",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "70a6d8ad-654a-464d-a445-7f1973a603c3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ddbe526b-74f8-4d97-878a-c90bb630657f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b43dad27-06c0-433c-b370-944617c6c675",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4d2c6cdf-1896-4afc-9d06-2cd5e83bb778",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5a7475ea-c9f8-4ec3-8328-44e1dcfb75c4",
                "ordinal": 3
              }
            ],
            "lineageTag": "d0262bad-32f9-4476-92fc-379b96572dc1"
          }
        ],
        "isHidden": true,
        "lineageTag": "383a9cbd-ba32-4c7f-9fa1-6a0b843ace4b",
        "partitions": [
          {
            "name": "LocalDateTable_a51c7a4b-f256-47be-a62f-1151859bf39c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ExterneDetails'[DatArr])), 1, 1), Date(Year(MAX('ExterneDetails'[DatArr])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Bloc_H",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Heure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca7adf4c-61ee-444d-82a2-673e0f3d635e",
            "sourceColumn": "Heure",
            "summarizeBy": "sum"
          },
          {
            "name": "Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cbcb26a6-8149-412e-9b1c-e0641fcbb9cf",
            "sourceColumn": "Nbr",
            "summarizeBy": "sum"
          },
          {
            "name": "DateD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8ef7c1c2-2980-4c05-86d3-0d6020ec0157",
            "sourceColumn": "DateD",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b50ce89e-43cd-4a77-b611-c18a5385677a"
                },
                "isDefault": true,
                "relationship": "8fea01ec-6a72-4a63-b70c-aa94d787847d"
              }
            ]
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DAY(Bloc_H[DateD])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1dee970c-b7fa-4ea2-8864-1ea82182c419",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Heuree",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "Bloc_H[Heure]& \"H\" ",
            "isDataTypeInferred": true,
            "lineageTag": "875b53f0-2173-4e3f-92a1-b04ada50c13e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "abd2a214-6132-47b1-8741-7dd433e2dd9b",
        "measures": [
          {
            "name": "J",
            "expression": [
              "",
              "VAR a =CALCULATE(SUM('Bloc_H'[Nbr]),'Bloc_H'[DateD] = today())",
              "RETURN IF(ISBLANK(a),0,a)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d7f70360-86fd-401a-8966-b6474cce0c44"
          },
          {
            "name": "J-1",
            "expression": [
              "",
              "VAR a =",
              "    CALCULATE(",
              "        SUM('Bloc_H'[Nbr]),",
              "        'Bloc_H'[DateD] = TODAY()-1",
              "    )",
              "    RETURN IF(ISBLANK(a),0,a)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1dca1c88-e481-4819-bc30-5d108e27e461"
          },
          {
            "name": "Nbr occupation",
            "expression": "SUM(Bloc_H[Nbr])",
            "formatString": "0",
            "lineageTag": "7591af14-d67c-415e-b9e3-6cb049dc6cd1"
          }
        ],
        "partitions": [
          {
            "name": "Bloc_H",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Bloc_H = Source{[Schema=\"dbo\",Item=\"Bloc_H\"]}[Data]",
                "in",
                "    dbo_Bloc_H"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b50ce89e-43cd-4a77-b611-c18a5385677a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7f9cc27f-262b-4482-856b-807332064fb8",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "fe28d921-371f-4052-8a6e-ce4e8b5fedf4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6db07458-6f27-473e-9bae-4364fc17bf8e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4cebd363-e8e2-460e-a8ec-c9d932a92500",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "410c675b-c99c-455a-8f0b-cddf58e86b46",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3cf664b3-d23b-436e-a12f-50db45c55b04",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4c9ddc85-4968-482e-b2d8-a79938d199e2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d98f04c9-b89a-46b9-9ae8-c5093b8ca396",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bc7d620a-e47e-4dc7-98ed-43cd7bdd3b54",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f5f1935e-59d2-451f-b265-29b6f48742f8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b6cda2df-7e09-40fa-8f0c-4327e014362b",
                "ordinal": 3
              }
            ],
            "lineageTag": "8e27bc0a-bb29-419f-82c5-715ef82e1b07"
          }
        ],
        "isHidden": true,
        "lineageTag": "fbee6628-6c9c-4654-99fd-1fcf4cb0237a",
        "partitions": [
          {
            "name": "LocalDateTable_b50ce89e-43cd-4a77-b611-c18a5385677a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Bloc_H'[DateD])), 1, 1), Date(Year(MAX('Bloc_H'[DateD])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Vtendance",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5cb2a79e-ac08-4211-8ccd-19bbc94bfbf2",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89ba28fc-e910-45f0-a2b0-e4f6abd613b5",
            "sourceColumn": "annee",
            "summarizeBy": "sum"
          },
          {
            "name": "realiser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e61aca67-48bc-4051-ba6f-0b28259b8831",
            "sourceColumn": "realiser",
            "summarizeBy": "sum"
          },
          {
            "name": "planifier_non_realiser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ecb740f1-b416-4a46-b513-8161d7abe3f3",
            "sourceColumn": "planifier_non_realiser",
            "summarizeBy": "sum"
          },
          {
            "name": "heure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c149248e-b818-47ce-8751-b3ffe621ae81",
            "sourceColumn": "heure",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "cb628628-c829-4f17-b8a7-d25a6e21e179",
        "measures": [
          {
            "name": "Nombre actes",
            "expression": "SUM(Vtendance[realiser])",
            "formatString": "0",
            "lineageTag": "48e2923d-4171-49f9-8e99-f9d9ef38d68d"
          }
        ],
        "partitions": [
          {
            "name": "Vtendance",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vtendance = Source{[Schema=\"dbo\",Item=\"Vtendance\"]}[Data]",
                "in",
                "    dbo_Vtendance"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VTracabilité",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86860b52-3f88-4003-8c28-208a64046fd2",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b5275f06-924f-43d2-bdb2-28bde46a9577",
            "sourceColumn": "annee",
            "summarizeBy": "sum"
          },
          {
            "name": "mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b9fd938b-5289-45fc-9f98-735c4561e6bd",
            "sourceColumn": "mois",
            "summarizeBy": "none"
          },
          {
            "name": "realiser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fec7da72-d29a-453b-9bb8-52d09cbbda55",
            "sourceColumn": "realiser",
            "summarizeBy": "sum"
          },
          {
            "name": "planifier_non_realiser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d25db749-86a9-4c2c-bb93-db3d553bcbd4",
            "sourceColumn": "planifier_non_realiser",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ddcecaa7-9eb3-4d84-a2e0-f45351851162",
        "measures": [
          {
            "name": "Sum realsié",
            "expression": "SUM('VTracabilité'[realiser])",
            "formatString": "0",
            "lineageTag": "6e66c720-be69-434d-95c5-c983f4745951"
          },
          {
            "name": "Sum planifier non realisé",
            "expression": "SUM('VTracabilité'[planifier_non_realiser])",
            "formatString": "0",
            "lineageTag": "7616ecbf-91a4-4275-93db-1e743c7733f9"
          },
          {
            "name": "Title",
            "expression": "\"Tracabilité du bloc de l année \" & SELECTEDVALUE('VTracabilité'[annee])",
            "lineageTag": "18f9b656-7d28-48c5-ba8d-5737ede7c643"
          }
        ],
        "partitions": [
          {
            "name": "VTracabilité",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VTracabilité = Source{[Schema=\"dbo\",Item=\"VTracabilité\"]}[Data]",
                "in",
                "    dbo_VTracabilité"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VCa_Realisé",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b3b85594-5841-4706-b3f0-9d0808d7d689",
            "sourceColumn": "Indice",
            "summarizeBy": "sum"
          },
          {
            "name": "des",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3629993-82d5-4eec-b448-709502b882ba",
            "sourceColumn": "des",
            "summarizeBy": "none"
          },
          {
            "name": "DatOpe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "60bb32ad-9173-4c79-9154-545d38fdf255",
            "sourceColumn": "DatOpe",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dae2407d-90ea-45ff-bbe1-34a10c573343"
                },
                "isDefault": true,
                "relationship": "8b7a8b41-cdbf-4bf2-b761-8f1b943488ee"
              }
            ]
          }
        ],
        "lineageTag": "eeb983b4-a0f5-475a-9a7c-1347c7ea8e72",
        "measures": [
          {
            "name": "CA realisé J",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "Var maxdate=CALCULATE(MAX('VCa_Realisé'[DatOpe]),all('VCa_Realisé'))",
              "return",
              "CALCULATE(SUM('VCa_Realisé'[Indice]),FILTER('VCa_Realisé','VCa_Realisé'[DatOpe]=maxdate))"
            ],
            "formatString": "#,0",
            "lineageTag": "87e121ba-154a-438d-9ddb-0d028711b9c9"
          },
          {
            "name": "Ca realisé prd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM('VCa_Realisé'[Indice])",
            "formatString": "#,0",
            "lineageTag": "212469c9-c610-4f8a-9acb-d4f43761876f"
          },
          {
            "name": "Ca realisé LastPeriod",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE([Ca realisé prd],SAMEPERIODLASTYEAR('VCa_Realisé'[DatOpe].[Date]))",
            "formatString": "#,0",
            "lineageTag": "0480f9e6-75d1-40b5-a6fb-aee63dc836e6"
          }
        ],
        "partitions": [
          {
            "name": "VCa_Realisé",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VCa_Realisé = Source{[Schema=\"dbo\",Item=\"VCa_Realisé\"]}[Data]",
                "in",
                "    dbo_VCa_Realisé"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_dae2407d-90ea-45ff-bbe1-34a10c573343",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "67598050-e35c-4d9f-b9cd-694a68e44fb1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "13ac360a-9de6-400d-a5e7-2a31a9428510",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3c232d79-0530-43ac-9c0b-e86cb403cce0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6cebd336-8ea2-4dc3-a8aa-1b82554a705c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b052e368-6e17-48d4-a117-26088bb39d80",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9d8590e5-5c08-44d5-8244-dfded7dd8ffa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "688993b3-2ec5-438e-afa4-d387c504e284",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "67e557c3-0cc3-43b9-9338-bc02d36891a7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5a84ec8b-f140-4051-9b29-6b11e0a38cb3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "67290375-edf0-4eb9-b9b2-cd98b9c8a498",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9821094d-f136-4a28-87dd-6a433f7677ec",
                "ordinal": 3
              }
            ],
            "lineageTag": "fa3b9bd0-6549-490c-957f-e10f32ce94eb"
          }
        ],
        "isHidden": true,
        "lineageTag": "28b9542c-c784-4836-b498-db5e50553190",
        "partitions": [
          {
            "name": "LocalDateTable_dae2407d-90ea-45ff-bbe1-34a10c573343",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VCa_Realisé'[DatOpe])), 1, 1), Date(Year(MAX('VCa_Realisé'[DatOpe])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Vhospitalisé",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b780d222-9f67-4d34-a5f2-db7da47feb00",
            "sourceColumn": "jour",
            "summarizeBy": "none"
          },
          {
            "name": "nom_jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f0b74e1-03dc-4ba4-b027-09d8bd6c4ab7",
            "sourceColumn": "nom_jour",
            "summarizeBy": "none"
          },
          {
            "name": "nbr_adm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c9c448e-fb5a-47f2-9603-52c30b5945ef",
            "sourceColumn": "nbr_adm",
            "summarizeBy": "sum"
          },
          {
            "name": "ca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "727f1aa7-62bb-4998-9662-dbe99df284e2",
            "sourceColumn": "ca",
            "summarizeBy": "sum"
          },
          {
            "name": "ifsemaine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2dcacb32-b038-4fef-a35f-95688fd8bf4c",
            "sourceColumn": "ifsemaine",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6841124c-e594-423a-95c3-1b9a1d08852d",
        "measures": [
          {
            "name": "ca Hospitalisé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "sum('Vhospitalisé'[ca])",
            "formatString": "#,0",
            "lineageTag": "33b21702-1800-4c12-8ef3-77ff3b7d5382"
          },
          {
            "name": "nbr adm",
            "expression": "sum('Vhospitalisé'[nbr_adm])",
            "formatString": "0",
            "lineageTag": "4038ff29-e54f-4698-9f0d-a7dc725f37ca"
          },
          {
            "name": "nbr adm semaine",
            "expression": "CALCULATE(sum('Vhospitalisé'[nbr_adm]),FILTER('Vhospitalisé','Vhospitalisé'[ifsemaine]=1))",
            "formatString": "0",
            "lineageTag": "6ecd20b8-b7a5-4f32-b655-74ede652aa79"
          },
          {
            "name": "ca Hospitalisé semaine",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum('Vhospitalisé'[ca]),FILTER('Vhospitalisé','Vhospitalisé'[ifsemaine]=1))",
            "lineageTag": "4bbde8b0-a6a8-416b-b0b7-c89df80e955c"
          }
        ],
        "partitions": [
          {
            "name": "Vhospitalisé",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vhospitalisé = Source{[Schema=\"dbo\",Item=\"Vhospitalisé\"]}[Data]",
                "in",
                "    dbo_Vhospitalisé"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VPatient",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09aa07e1-a4bd-408c-9351-492bc78dc97b",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Valeur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "a497b071-c739-47e0-a060-1ebde9d5dd5d",
            "sourceColumn": "Valeur",
            "summarizeBy": "sum"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e859b4ca-1c61-4ca7-9473-e27e30a9f09a",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4fd1202f-e76d-4288-ba77-64cbdf12a223",
            "sourceColumn": "Annee",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7d0c16f7-fd09-46a1-bbba-9102cd47ad97",
        "measures": [
          {
            "name": "Nbr patient",
            "displayFolder": "Nationnalité",
            "expression": "CALCULATE(sum(VPatient[Valeur]),FILTER(VPatient,CONTAINSSTRING(VPatient[Description],\"nationalité\")))",
            "formatString": "0",
            "lineageTag": "5461e155-4272-4279-814e-3b9ff6fda036"
          },
          {
            "name": "Nb Patient tunisien",
            "displayFolder": "Nationnalité",
            "expression": "CALCULATE([Nbr patient], FILTER(VPatient,CONTAINSSTRING(VPatient[Type],\"marocains\")))",
            "formatString": "0",
            "lineageTag": "c7ebfe9c-df7f-4aa5-a4a5-4fe08dff8ff3"
          },
          {
            "name": "Nb Patient Libyen",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Nationnalité",
            "expression": [
              "Var a=CALCULATE([Nbr patient], FILTER(VPatient,CONTAINSSTRING(VPatient[Type],\"Libyen\")))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "59665cbb-892e-4cb5-bc3e-9c818cbc5ed5"
          },
          {
            "name": "Nb Patient Algérien",
            "displayFolder": "Nationnalité",
            "expression": [
              "var a =CALCULATE([Nbr patient], FILTER(VPatient,CONTAINSSTRING(VPatient[Type],\"Algérien\")))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "46d0a6fe-ae74-4c8a-8d1a-4c4935166174"
          },
          {
            "name": "Nb Patient autre",
            "displayFolder": "Nationnalité",
            "expression": "CALCULATE([Nbr patient], FILTER(VPatient,CONTAINSSTRING(VPatient[Type],\"autre\")))",
            "formatString": "0",
            "lineageTag": "e3cbea9c-a67d-4afd-8cf8-9472b45334a8"
          },
          {
            "name": "% tun",
            "displayFolder": "Nationnalité",
            "expression": "[Nb Patient tunisien]/[Nbr patient]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "0537b7f5-a008-49b3-8c5f-40cf2822c5a7"
          },
          {
            "name": "% Lyb",
            "displayFolder": "Nationnalité",
            "expression": "[Nb Patient Libyen]/[Nbr patient]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "ccb259ea-fb0d-459b-bb67-40401c5882e5"
          },
          {
            "name": "% alg",
            "displayFolder": "Nationnalité",
            "expression": "[Nb Patient Algérien]/[Nbr patient]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "879b7326-3404-450b-ac7d-60668e196913"
          },
          {
            "name": "% autre",
            "displayFolder": "Nationnalité",
            "expression": "[Nb Patient autre]/[Nbr patient]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "67ac84f8-0994-4316-8a9f-22bf79198921"
          },
          {
            "name": "nbr patients interne",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Interne",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"nb interne\"))",
            "formatString": "#,0",
            "lineageTag": "ea890b85-cec6-4985-aa97-c4d3b0511647"
          },
          {
            "name": "nbr nuité",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Interne",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,CONTAINSSTRING(VPatient[Description],\"nuité\")))",
            "formatString": "#,0",
            "lineageTag": "38edb86d-feac-43f8-9b41-e57fc3b0c9a7"
          },
          {
            "name": "CA patients interne",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Interne",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Description]=\"CA patients interne\"))",
            "lineageTag": "3a542c32-f283-46c0-9a00-023359db41ea"
          },
          {
            "name": "Montant Moyen Patient",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Interne",
            "expression": "[CA patients interne]/[nbr patients interne]",
            "formatString": "#,0",
            "lineageTag": "d0c5d3ba-b279-42e3-bfab-d963f6cd49e1"
          },
          {
            "name": "Moyenne Séjour patient",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Interne",
            "expression": "[nbr nuité]/[nbr patients interne]",
            "formatString": "0",
            "lineageTag": "fab0af4c-d9b5-493b-8baf-1e1b574295a6"
          },
          {
            "name": "Ca externe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Externe",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"ca externe\"))",
            "lineageTag": "abf6a346-dddc-47b5-bc44-ad7248ab5b5a"
          },
          {
            "name": "Nb externe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Externe",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"nb externe\"))",
            "formatString": "#,0",
            "lineageTag": "7e2881c6-d17f-488e-89a6-b243e2621aca"
          },
          {
            "name": "Montant Moyen par patient externe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Externe",
            "expression": "[Ca externe]/[Nb externe]",
            "lineageTag": "69fc2755-38d1-43ab-a0b5-137bfb8baa34"
          },
          {
            "name": "Décès",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Sortie",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Description]=\"Décès\"))",
            "formatString": "0",
            "lineageTag": "9ae04c01-47b5-4ea9-ba81-6cff99eb4d99"
          },
          {
            "name": "Fin du traitement",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Sortie",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Description]=\"Fin du traitement\"))",
            "formatString": "#,0",
            "lineageTag": "9639450a-7984-49b7-a88a-1ce018437a17"
          },
          {
            "name": "Transfert vers l'hôpital",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Sortie",
            "expression": [
              "var a=CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Description]=\"Transfert vers l'hôpital\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "#,0",
            "lineageTag": "348c945b-e74b-4fec-a901-3b97fdd332db"
          },
          {
            "name": "Transfert vers une autre clinique",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Sortie",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Description]=\"Transfert vers une autre clinique\"))",
            "formatString": "#,0",
            "lineageTag": "aac55ba0-c80b-41b1-8feb-cf46e68f079b"
          },
          {
            "name": "nb interne_externe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Nb externe]+[nbr patients interne]",
            "lineageTag": "18fe5434-60be-467a-b11d-2e7651c7aac4"
          },
          {
            "name": "% interne",
            "displayFolder": "Interne",
            "expression": "[nbr patients interne]/[nb interne_externe]",
            "formatString": "#,0\\ %;-#,0\\ %;#,0\\ %",
            "lineageTag": "275ea1d1-460c-4715-b19f-91405baef93f"
          },
          {
            "name": "% externe",
            "displayFolder": "Externe",
            "expression": "[Nb externe]/[nb interne_externe]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "32d35d49-6288-4d77-9616-815d16bc26ff"
          },
          {
            "name": "Nb Urgence",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Urgence",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"Nb Urgence\"))",
            "formatString": "#,0",
            "lineageTag": "d54006fa-9925-4b91-ad59-99d22e1b732d"
          },
          {
            "name": "Nb Urgence Hospitalisé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Urgence",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"Nb Urgence Hospitalisé\"))",
            "formatString": "#,0",
            "lineageTag": "bff156c7-67da-4cc1-9e51-e48c38758115"
          },
          {
            "name": "Nb Urgence examens externes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Urgence",
            "expression": [
              "var a =CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"Nb Urgence examens externes\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "#,0",
            "lineageTag": "5f12bcda-f9cc-4787-a395-156d6a0a0759"
          },
          {
            "name": "Nb Urgence sans examens externes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Urgence",
            "expression": "[Nb Urgence]-([Nb Urgence Hospitalisé]+[Nb Urgence examens externes])",
            "formatString": "#,0",
            "lineageTag": "e1e29f12-8159-431e-9c34-d1228f3c37b9"
          },
          {
            "name": "% urgence",
            "displayFolder": "Urgence",
            "expression": "[Nb Urgence Hospitalisé]/[Nb Urgence]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "567376f0-a87a-4de1-a8a2-1856253f9398"
          },
          {
            "name": "Nb Patient Readmis",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Readmis",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"Nb Patient Readmis\"))",
            "formatString": "#,0",
            "lineageTag": "fb1cfbc9-ec48-4c8d-be59-6b96fecbce6d"
          },
          {
            "name": "nbr patients Readmis Hospitalisés",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Readmis",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"nbr patients Readmis Hospitalisés\"))",
            "formatString": "#,0",
            "lineageTag": "6b37fe20-ad6d-452f-b85d-9438f92a2d4f"
          },
          {
            "name": "nbr patients Readmis Hopital de jour",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Readmis",
            "expression": [
              "var a=CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Type]=\"nbr patients Readmis Hopital de jour\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "3ff602d3-7042-43e8-9ffd-16ac0d93cf5b"
          },
          {
            "name": "nbr patients Readmis Hopital externes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Patient Readmis",
            "expression": "[Nb Patient Readmis]-([nbr patients Readmis Hopital de jour]+[nbr patients Readmis Hospitalisés])",
            "lineageTag": "68d4953d-cfb8-417e-84d3-1f96d325c415"
          },
          {
            "name": "%patient réadmis",
            "displayFolder": "Patient Readmis",
            "expression": "[Nb Patient Readmis]/[nb interne_externe]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "71e5448c-2acb-43f3-9f32-961f7d5916d0"
          },
          {
            "name": "Contre avis médical",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Patient Sortie",
            "expression": "CALCULATE(SUM(VPatient[Valeur]),FILTER(VPatient,VPatient[Description]=\"Contre avis médical\"))",
            "formatString": "0",
            "lineageTag": "9b9f454d-5b92-41a1-85e0-87642776e28a"
          }
        ],
        "partitions": [
          {
            "name": "VPatient",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VPatient = Source{[Schema=\"dbo\",Item=\"VPatient\"]}[Data]",
                "in",
                "    dbo_VPatient"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Vurgence",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Heure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c87e79d9-2d34-44da-a628-3ad88ec9e9bf",
            "sourceColumn": "Heure",
            "summarizeBy": "sum"
          },
          {
            "name": "Nombre de Semaines par Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKNUM(Vurgence[DatArr])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "55ab3606-2295-473c-9c20-9afe344ac2d8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "FORMAT(",
              "    'Vurgence'[datarr],",
              "    \"dddd\",\"fr-FR\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "df565b06-575a-45fb-ac40-b4af13868aaf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "463c8447-11f7-4d6b-b02a-024e890f8b54",
            "sourceColumn": "nb",
            "summarizeBy": "sum"
          },
          {
            "name": "DatArr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8ad2e3a5-693c-400f-af49-9aaa526e954a",
            "sourceColumn": "DatArr",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_69ee96d6-e8f8-4333-a0f0-ef23fbc1a166"
                },
                "isDefault": true,
                "relationship": "2ab5b14b-a4dc-4dc0-9975-311f952177ff"
              }
            ]
          },
          {
            "name": "mnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "364a30ea-2be3-47c1-9b0b-0400c6177c89",
            "sourceColumn": "mnt",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "643c1db1-086b-4cee-ac32-c28290915673",
        "measures": [
          {
            "name": "Nb urgence Jour/H",
            "expression": [
              "Var Maxdate=TODAY()",
              "RETURN",
              "CALCULATE(sum(Vurgence[nb]),Vurgence[DatArr]=Maxdate)"
            ],
            "formatString": "0",
            "lineageTag": "e3b04586-f9bb-46eb-8ff5-0c2bd7687d1b"
          },
          {
            "name": "Nb Vurgence",
            "expression": "SUM(Vurgence[nb])",
            "formatString": "0",
            "lineageTag": "91de2695-7c4e-47e3-b98a-6d222456e7b1"
          },
          {
            "name": "CARealise Vurgence",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(Vurgence[mnt])",
            "formatString": "#,0",
            "lineageTag": "a31d724f-5ad6-4581-a787-392ef1532d02"
          },
          {
            "name": "nbr admissUrgence/semaine",
            "expression": [
              "VAR LastDay = CALCULATE(Max('Vurgence'[Nombre de Semaines par Mois]), ALL('Vurgence'))",
              "RETURN",
              "    CALCULATE(",
              "        [Nb Vurgence],",
              "        'Vurgence'[Nombre de Semaines par Mois] = LastDay",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "1105fd03-e48f-45b7-aa02-45a3224b23ae"
          },
          {
            "name": "CARealise Vurgence/Semainde",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR LastDay = CALCULATE(Max('Vurgence'[Nombre de Semaines par Mois]), ALL('Vurgence'))",
              "RETURN CALCULATE(SUM(Vurgence[mnt]),FILTER(Vurgence,Vurgence[Nombre de Semaines par Mois]=LastDay))"
            ],
            "formatString": "#,0",
            "lineageTag": "3ad3238c-6ae7-44ef-85a9-f928ded4ccbc"
          }
        ],
        "partitions": [
          {
            "name": "Vurgence",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vurgence = Source{[Schema=\"dbo\",Item=\"Vurgence\"]}[Data]",
                "in",
                "    dbo_Vurgence"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VHopitalJour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67a04b0f-e923-4b3b-b29d-c63e5ee95370",
            "sourceColumn": "jour",
            "summarizeBy": "none"
          },
          {
            "name": "nom_jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67f81b17-0949-498d-b8d8-cd1896239866",
            "sourceColumn": "nom_jour",
            "summarizeBy": "none"
          },
          {
            "name": "nbr_adm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ba3d6e9-56ef-4559-8543-bf40fb5f40fa",
            "sourceColumn": "nbr_adm",
            "summarizeBy": "sum"
          },
          {
            "name": "ca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6c6567b1-432f-4d76-a702-baf0df39f004",
            "sourceColumn": "ca",
            "summarizeBy": "sum"
          },
          {
            "name": "ifsemaine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a69eef85-6ada-4533-be04-8b8c7d6624b8",
            "sourceColumn": "ifsemaine",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7840e370-8bd6-4bb8-9860-1284d4086a9f",
        "measures": [
          {
            "name": "Sum AD HJ",
            "expression": "SUM(VHopitalJour[nbr_adm])",
            "formatString": "#,0",
            "lineageTag": "51359d4f-016d-4250-91ca-fee4f40665ea"
          },
          {
            "name": "CA Realisé HJ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(VHopitalJour[ca])",
            "formatString": "#,0",
            "lineageTag": "fb044bb8-a924-4104-9b6c-36f3ecf0fd5e"
          },
          {
            "name": "nbr admiss/semaine HJ",
            "expression": "CALCULATE(sum('VHopitalJour'[nbr_adm]),FILTER(VHopitalJour,VHopitalJour[ifsemaine]=1))",
            "formatString": "#,0",
            "lineageTag": "7010db6b-d58a-45f9-93e9-af2bbe6a4f6c"
          },
          {
            "name": "CA admiss/semaine HJ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(sum('VHopitalJour'[ca]),FILTER(VHopitalJour,VHopitalJour[ifsemaine]=1))",
            "formatString": "#,0",
            "lineageTag": "942feda3-6fb8-44b1-96eb-3f802d66d204"
          }
        ],
        "partitions": [
          {
            "name": "VHopitalJour",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VHopitalJour = Source{[Schema=\"dbo\",Item=\"VHopitalJour\"]}[Data]",
                "in",
                "    dbo_VHopitalJour"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VDetails_CA_Facture",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "mnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "20231f7e-ce18-4d2f-8f13-f48fb34b84ad",
            "sourceColumn": "mnt",
            "summarizeBy": "sum"
          },
          {
            "name": "DesFam",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6309136-33bf-468a-be54-eca835ebc5f2",
            "sourceColumn": "DesFam",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a31bcefc-9172-4680-8314-bba78dc6380d",
        "measures": [
          {
            "name": "title Ca facture",
            "expression": "\"Récapitulatif de l'année \" & YEAR(TODAY())",
            "lineageTag": "c9924126-3d74-4f7c-8459-91a45b555a89"
          },
          {
            "name": "mnt caFact",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(VDetails_CA_Facture[mnt])",
            "lineageTag": "92cca44a-16dc-4156-a9d5-9f8b6137f0f1"
          }
        ],
        "partitions": [
          {
            "name": "VDetails_CA_Facture",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VDetails_CA_Facture = Source{[Schema=\"dbo\",Item=\"VDetails_CA_Facture\"]}[Data]",
                "in",
                "    dbo_VDetails_CA_Facture"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Vtop5_Dep",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "456e9852-6f6e-41a8-9b99-6eb4b8100053",
            "sourceColumn": "dep",
            "summarizeBy": "none"
          },
          {
            "name": "consommation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b61cc3ea-32e2-4f76-87b5-3c30b23819a5",
            "sourceColumn": "consommation",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9ed62f75-f527-463f-95e4-0bcb7da7448a",
        "measures": [
          {
            "name": "consommationSum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(Vtop5_Dep[consommation])",
            "formatString": "0",
            "lineageTag": "0a20f4b9-51cb-486c-a220-392b511d0923"
          }
        ],
        "partitions": [
          {
            "name": "Vtop5_Dep",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vtop5_Dep = Source{[Schema=\"dbo\",Item=\"Vtop5_Dep\"]}[Data]",
                "in",
                "    dbo_Vtop5_Dep"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Vconsommation_M",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8808d170-4d3f-4bcd-9ef0-13f8d2417563",
            "sourceColumn": "mois",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b28cdeaa-eec5-41ec-a395-81e95c4b4bc7",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d329594-7929-46ca-907a-3a66cec175e2",
            "sourceColumn": "nbr",
            "summarizeBy": "none"
          },
          {
            "name": "des",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4801d3f-2227-48e4-85c7-046e7b4d0a98",
            "sourceColumn": "des",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "049f0d75-de7e-4a49-b728-ef22dfe562a4",
        "measures": [
          {
            "name": "Current Mnt",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "Var a =CALCULATE(sum(Vconsommation_M[nbr]),FILTER(Vconsommation_M,Vconsommation_M[id]=MONTH(TODAY())-1))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "e2161a84-58d3-46df-9489-deba0e890a0e"
          },
          {
            "name": "MontantSum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(Vconsommation_M[nbr])",
            "formatString": "#,0",
            "lineageTag": "ad9c27bb-db44-4086-ad64-082fb81e3ad6"
          },
          {
            "name": "Titre",
            "expression": [
              "",
              "\"Economat : \" & ",
              "FORMAT(",
              "    EDATE(TODAY(), -1),",
              "    \"MMMM yyyy\"",
              ")"
            ],
            "lineageTag": "d016afd6-078c-4dcd-b659-5c9b4fef4b9e"
          }
        ],
        "partitions": [
          {
            "name": "Vconsommation_M",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vconsommation_M = Source{[Schema=\"dbo\",Item=\"Vconsommation_M\"]}[Data]",
                "in",
                "    dbo_Vconsommation_M"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VCompta",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96d5cfa3-3e1f-49ab-93ad-464a38ebb609",
            "sourceColumn": "title",
            "summarizeBy": "none"
          },
          {
            "name": "Result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4874f07-105c-4e28-8f6f-96401f289901",
            "sourceColumn": "Result",
            "summarizeBy": "sum"
          },
          {
            "name": "annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ebf7c8e-c3dc-4970-92f5-cb485a99ef19",
            "sourceColumn": "annee",
            "summarizeBy": "sum"
          },
          {
            "name": "text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b694694-6931-477e-a428-95561d635078",
            "sourceColumn": "text",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7f3dd64f-9add-4085-af8d-8057c5a8764b",
        "measures": [
          {
            "name": "Tresorerie Manuelle",
            "expression": [
              "Var a= CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Tresorerie_Manuelles\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "83b42bc3-177a-480f-8e87-a03865c97b11"
          },
          {
            "name": "Tresorerie_Intgerer",
            "expression": [
              "var a =CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Tresorerie_Intgerer\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "08606909-82ed-4aea-b914-7eb42a82ac9a"
          },
          {
            "name": "Decaissement_Intgerer",
            "expression": [
              "var a = CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Decaissement_Intgerer\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "e169224b-e94c-453e-a215-d688e3f847cf"
          },
          {
            "name": "Decaissement_Manuelles",
            "expression": [
              "var a = CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Decaissement_Manuelles\"))",
              "RETURN IF(ISBLANK(a),0)"
            ],
            "formatString": "0",
            "lineageTag": "e0e3e5fd-1f20-451c-a791-6f172ff706b2"
          },
          {
            "name": "Encaissement_Manuelles",
            "expression": [
              "var a=CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Encaissement_Manuelles\"))",
              "RETURN IF(ISBLANK(a),0)"
            ],
            "formatString": "0",
            "lineageTag": "40e28ea3-f0f8-43f6-b581-1b8d475dec48"
          },
          {
            "name": "Encaissement_Intgerer",
            "expression": [
              "var a=CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Encaissement_Intgerer\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "690dd1d6-ad6a-4a2e-a98b-4602e1b23e48"
          },
          {
            "name": "Encaissement",
            "expression": [
              "var a =CALCULATE(SUM(VCompta[Result]),CONTAINSSTRING(VCompta[title],\"Encaissement\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "a0680279-264f-47d5-91f6-00a9cce7ef84"
          },
          {
            "name": "Decaissement",
            "expression": [
              "var a = CALCULATE(SUM(VCompta[Result]),CONTAINSSTRING(VCompta[title],\"Decaissement\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "bef8dbe7-915d-49d7-8c49-7d20a02e0ece"
          },
          {
            "name": "Tresorerie",
            "expression": [
              "var a = CALCULATE(SUM(VCompta[Result]),CONTAINSSTRING(VCompta[title],\"Tresorerie\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "2de7365b-1e43-46bc-9433-6cc37a7cf0cf"
          },
          {
            "name": "Achat_Intgerer",
            "expression": [
              "var a= CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Achat_Intgerer\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "a9a093e7-eaef-4ffa-933b-aa81d3e24e04"
          },
          {
            "name": "Achat_Manuelles",
            "expression": [
              "var a=CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Achat_Manuelles\"))",
              "RETURN IF(ISBLANK(a),0)"
            ],
            "formatString": "0",
            "lineageTag": "d3eda086-71fa-4022-bd6e-cf085198ce91"
          },
          {
            "name": "Achat",
            "expression": [
              "var a =CALCULATE(SUM(VCompta[Result]),CONTAINSSTRING(VCompta[title],\"Achat\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "bd255695-76ef-47aa-9446-3d97f92c5e2e"
          },
          {
            "name": "Autre_Intgerer",
            "expression": [
              "var a = CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Autre_Intgerer\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "5dbd05bf-ab07-4ada-b2ac-946aca7aa9d7"
          },
          {
            "name": "Autre_Manuelles",
            "expression": [
              "Var A=CALCULATE(SUM(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Autre_manuelle\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "e2693c70-c9f2-4bd1-b962-23469ac060b6"
          },
          {
            "name": "Autre",
            "expression": [
              "var a= CALCULATE(SUM(VCompta[Result]),CONTAINSSTRING(VCompta[title],\"Autre\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "5a52c8b3-32a8-4b8b-ad8d-98dc9623ca47"
          },
          {
            "name": "Date derniére Generation",
            "expression": "CALCULATE(SELECTEDVALUE(VCompta[text]),FILTER(VCompta,VCompta[title]=\"DernierDateGener\"))",
            "lineageTag": "9bd4c5e7-f887-4f6f-a11b-0774a3e9fdf7"
          },
          {
            "name": "Nombre ecriture comptable",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a= CALCULATE(sum(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Nbr_ecritures\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "#,0",
            "lineageTag": "dc1eb31d-527d-49f6-9384-70dcd9c1dbf3"
          },
          {
            "name": "Nombre ecriture comptable manuelle",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "ABS([Nombre ecriture comptable]-[Nombre ecriture comptable automatique])",
            "formatString": "#,0",
            "lineageTag": "3f5f1c28-7b50-4880-98e8-14c6ef6c8b2b"
          },
          {
            "name": "Nombre ecriture comptable automatique",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a= CALCULATE(sum(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Nbr_ecritures_Integrées\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "#,0",
            "lineageTag": "71475e37-13f2-4f4a-8eec-b9d079c3a9cd"
          },
          {
            "name": "Nombre ecriture CA",
            "expression": [
              "var a =CALCULATE(sum(VCompta[Result]),CONTAINSSTRING(VCompta[title],\"Vente\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "24ff180f-9536-41d4-a0c0-114f865c846d"
          },
          {
            "name": "Nombre ecriture CA Automatique",
            "expression": [
              "var a=CALCULATE(sum(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Vente_Integrées\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "8a54ac0c-30ba-4c2a-924d-c09a6fdda1f6"
          },
          {
            "name": "Nombre ecriture CA manuelle",
            "expression": [
              "Var a= CALCULATE(sum(VCompta[Result]),FILTER(VCompta,VCompta[title]=\"Vente_Manuelles\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "8c966b1f-0747-4369-a1d0-9b3d8875c093"
          }
        ],
        "partitions": [
          {
            "name": "VCompta",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VCompta = Source{[Schema=\"dbo\",Item=\"VCompta\"]}[Data]",
                "in",
                "    dbo_VCompta"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VMasse_Salariale_CA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CA facturé M-1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bbd73936-79ee-4c0f-a392-723c9c5b8c96",
            "sourceColumn": "CA facturé M-1",
            "sourceProviderType": "decimal(38, 3)",
            "summarizeBy": "sum"
          },
          {
            "name": "CA réalisé M-1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "69e6c3d7-1870-4784-ad52-df62d266a19d",
            "sourceColumn": "CA réalisé M-1",
            "sourceProviderType": "decimal(38, 11)",
            "summarizeBy": "sum"
          },
          {
            "name": "Masse Salariale / CA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "d6b19d2f-c69e-4025-868e-f68de2f86441",
            "sourceColumn": "Masse Salariale / CA",
            "sourceProviderType": "decimal(38, 8)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b9812f89-7949-45bf-adbf-f7fce2aac542",
        "partitions": [
          {
            "name": "VMasse_Salariale_CA",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VMasse_Salariale_CA = Source{[Schema=\"dbo\",Item=\"VMasse_Salariale_CA\"]}[Data]",
                "in",
                "    dbo_VMasse_Salariale_CA"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Alertes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "138053a0-602f-446b-a2de-b7a09a795149",
            "sourceColumn": "Description",
            "sourceProviderType": "varchar(18)",
            "summarizeBy": "none"
          },
          {
            "name": "indice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "8ab62fc8-59d5-4bef-9933-d9b56338645f",
            "sourceColumn": "indice",
            "sourceProviderType": "decimal(38, 11)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9a7b05f9-489d-4d27-a072-fef982367189",
        "measures": [
          {
            "name": "Prct",
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Ca manuelle saisie\"))/CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Ca Realisé\"))",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "05a2de11-34ca-4a36-95db-bc81f0e8ca55"
          },
          {
            "name": "Ca manuelle saisie",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Ca manuelle saisie\"))",
            "formatString": "0",
            "lineageTag": "a3e7f7e8-1703-4a1d-a764-70a3f6380195"
          },
          {
            "name": "cumul passager",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"cumul passager\"))",
            "formatString": "#,0",
            "lineageTag": "a32e03a1-97b8-444e-9ac4-fce58a1ae15c"
          },
          {
            "name": "CA Sortants Non Facturés",
            "expression": "CALCULATE( FORMAT(SUM('Alertes'[indice]) / 1000, \"#,###K\"),FILTER(Alertes,Alertes[Description]=\"CA Sortants Non Facturés\"))",
            "lineageTag": "33d31689-d20c-486c-9d3d-fac5b2052962"
          },
          {
            "name": "En instance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"En instance\"))",
            "formatString": "0",
            "lineageTag": "9a6d2de1-3183-404b-86a1-65aa581a6b49"
          },
          {
            "name": "Sortants non facturés",
            "expression": "[CA Sortants Non Facturés] & \"/\" & [En instance]",
            "lineageTag": "4b430935-4161-44f1-a958-781629316fb7"
          },
          {
            "name": "factures ouvertes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"factures ouvertes\"))",
            "formatString": "0",
            "lineageTag": "5d0af567-5843-4ff1-8d50-84cc8acf7352"
          },
          {
            "name": "Facture_non_receptionnee",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Facture_non_receptionnee\"))",
            "formatString": "0",
            "lineageTag": "b106c5be-508e-4a6d-8562-9890ab7a782b"
          },
          {
            "name": "Facture_non_envoye",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Facture_non_envoye\"))",
            "formatString": "0",
            "lineageTag": "31577afa-0d38-44ca-ad21-db494b50eab2"
          },
          {
            "name": "Total des créances net",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Total des créances net\"))",
            "formatString": "#,0",
            "lineageTag": "159a8bf1-4605-4bca-b5c9-1217a9a7304a"
          },
          {
            "name": "Impayées PEC >6 mois",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "var a =CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Impayées PEC >6 mois\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "#,0",
            "lineageTag": "0b6ee2da-2819-40f1-b7bb-3afa8695593a"
          },
          {
            "name": "chéques contentieux",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "var a=CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"chéques contentieux\"))",
              "return IF(ISBLANK(a),0,a)"
            ],
            "lineageTag": "c24a86e4-ea9d-4970-8144-6135be98331f"
          },
          {
            "name": "Trop moins perçu",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Trop moins perçu\"))",
            "lineageTag": "a9943b1e-f181-4b04-a386-a624bd183fb9"
          },
          {
            "name": "Factures impayées j-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "var a=CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Factures impayées j-1\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "#,0",
            "lineageTag": "5bb63437-21e6-4657-8b37-ee26cca046b2"
          },
          {
            "name": "dossier non cloturé j-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"dossier non cloturé j-1\"))",
            "formatString": "#,0",
            "lineageTag": "e14a82c3-66af-4870-aa3a-cd48ae1a018a"
          },
          {
            "name": "Supp_Pharmacies",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Supp Pharmacie\"))",
            "formatString": "0",
            "lineageTag": "2e3ce95d-4b7f-461f-8c2f-a2114469443a"
          },
          {
            "name": "Supp_Actes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Supp Actes\"))",
            "formatString": "0",
            "lineageTag": "55f77a76-17b6-4fd3-815f-7a0cf88ba53d"
          },
          {
            "name": "Supp_Autres",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Alertes[indice]),FILTER(Alertes,Alertes[Description]=\"Supp Autres\"))",
            "formatString": "#,0",
            "lineageTag": "9f3c3814-04db-4ac8-9fef-68b71b3da567"
          }
        ],
        "partitions": [
          {
            "name": "Alertes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Alertes = Source{[Schema=\"dbo\",Item=\"Alertes\"]}[Data]",
                "in",
                "    dbo_Alertes"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Requête1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3a80ac73-f900-49ab-8cef-5a3ded00cfb4",
            "sourceColumn": "Column1",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_02ff1113-7a7e-4474-bba1-bdccd862917e"
                },
                "isDefault": true,
                "relationship": "1b3e999e-4850-4d23-b9ac-377b5e1fbb77"
              }
            ]
          }
        ],
        "lineageTag": "15edd06b-8aa1-443b-a81e-f9b723d9e032",
        "measures": [
          {
            "name": "dettes Fournisseurs economat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(V_Achat_Stock[Valeur]),CONTAINSSTRING(V_Achat_Stock[Nature],\"dettes Fournisseur economat\"))",
            "formatString": "#,0",
            "lineageTag": "528c858e-d469-4bc8-ab90-8a4779d7743f"
          },
          {
            "name": "dettes Fournisseurs Immo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(V_Achat_Stock[Valeur]),CONTAINSSTRING(V_Achat_Stock[Nature],\"dettes Fournisseur Immo\"))",
            "formatString": "#,0",
            "lineageTag": "588caa0b-b75b-4656-8773-874063e0f111"
          },
          {
            "name": "dettes Fournisseurs Pharmacie",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(V_Achat_Stock[Valeur]),CONTAINSSTRING(V_Achat_Stock[Nature],\"dettes Fournisseurs Pharmacie\"))",
            "formatString": "#,0",
            "lineageTag": "0161b843-c7a5-483d-8221-cfcbc5b7b85a"
          },
          {
            "name": "Sum Achat",
            "expression": "SUM(V_achat_Stock[Valeur])",
            "formatString": "#,0",
            "lineageTag": "6cec9128-4615-414b-8889-a409f0c57c90"
          },
          {
            "name": "Title achat",
            "expression": "\"Valeurs achats \"& YEAR(TODAY())",
            "lineageTag": "8549f2a1-235a-44b8-a919-404f141c6876"
          }
        ],
        "partitions": [
          {
            "name": "Requête1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow(),",
                "    #\"Converti en table\" = #table(1, {{Source}}),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Converti en table\",{{\"Column1\", type datetime}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_02ff1113-7a7e-4474-bba1-bdccd862917e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "850341a3-ac4e-4ac7-be74-6a10152d452f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5d4c2508-260a-4be6-8fa4-873d28b51744",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9c1a8307-98bf-423d-ad3a-c6e7435dfabf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "48a17544-cd10-4bfb-bfbc-8cd04c40ea2b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "76849a4a-5574-4e61-9ed0-c36e2e01a3a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6ef05276-add8-4882-b820-3518d4445cb3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "17555162-4113-4ce8-8588-48436f5a2004",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b707532b-864e-4a6b-88ec-e9c91a2a2331",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f90ce1a1-4412-4d4f-b3bf-9332c184bca4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b24d4e7c-74aa-4d43-a960-685b1a13d0e2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dca91cda-0703-4bfb-bb5c-5bafd9974283",
                "ordinal": 3
              }
            ],
            "lineageTag": "c26336ab-6fd7-44cb-803d-2ed6bb2f3fd7"
          }
        ],
        "isHidden": true,
        "lineageTag": "43815478-c68f-4c7f-85ce-2ae15143c269",
        "partitions": [
          {
            "name": "LocalDateTable_02ff1113-7a7e-4474-bba1-bdccd862917e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Requête1'[Column1])), 1, 1), Date(Year(MAX('Requête1'[Column1])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VDettes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7e216f4-2db9-4828-9a24-de89a6704ca2",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Valeur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "089c84a1-76ca-4777-8447-354f36cbd761",
            "sourceColumn": "Valeur",
            "summarizeBy": "sum"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8e38baa-8b16-4533-91c8-be16c4378c26",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Nature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ec1b1ff-c021-465a-a8e5-56924adaac46",
            "sourceColumn": "Nature",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d7666063-d744-4bcc-a78b-80020659d4a2",
        "measures": [
          {
            "name": "Total factures echues",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(VDettes[Valeur]),FILTER(VDettes,VDettes[Code]=\"echus\"))",
            "formatString": "#,0",
            "lineageTag": "e7414c8e-eb1c-4eee-9441-fc6c5ffa2f3b"
          },
          {
            "name": "Bons de réception non facturée",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(VDettes[Valeur]),FILTER(VDettes,VDettes[Code]=\"BonRecp\"))",
            "formatString": "#,0",
            "lineageTag": "2fe25550-7b36-4af2-be07-b54cd07c8f3b"
          },
          {
            "name": "Total factures non réglées",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(VDettes[Valeur]),FILTER(VDettes,VDettes[Code]=\"total\"))",
            "formatString": "#,0",
            "lineageTag": "5f0e8289-947b-44d7-ace1-c081301e25da"
          }
        ],
        "partitions": [
          {
            "name": "VDettes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vdettes = Source{[Schema=\"dbo\",Item=\"VDettes\"]}[Data]",
                "in",
                "    dbo_Vdettes"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VFacturation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "des",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f93d6b5-f629-42fb-92a3-97c9aed11d4f",
            "sourceColumn": "des",
            "summarizeBy": "none"
          },
          {
            "name": "Heure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50064604-c7c3-43ae-8785-c92bd2835eb1",
            "sourceColumn": "Heure",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bec75e3c-c4ba-41e7-a6f2-b8dcb77c5b5e",
        "measures": [
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "var a= SELECTEDVALUE(VFacturation[Heure])",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "1844bc0a-4c80-4f04-84c0-69cc81ed6be3"
          }
        ],
        "partitions": [
          {
            "name": "VFacturation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VFacturation = Source{[Schema=\"dbo\",Item=\"VFacturation\"]}[Data]",
                "in",
                "    dbo_VFacturation"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_Marge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "609209c5-ba79-49c6-b25e-be6036ca41c3",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Vente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6686d714-4140-412f-9c02-f210bf05ccb0",
            "sourceColumn": "Vente",
            "summarizeBy": "sum"
          },
          {
            "name": "quantite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27db9b45-c4ff-452f-93c6-e25fa254c5a6",
            "sourceColumn": "quantite",
            "summarizeBy": "sum"
          },
          {
            "name": "achat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fbd7b7b8-a399-4fa9-9a54-4185f2b9987d",
            "sourceColumn": "achat",
            "summarizeBy": "sum"
          },
          {
            "name": "Désignation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14682aa1-e0a8-4829-bc44-1b12ee7bd27d",
            "sourceColumn": "Désignation",
            "summarizeBy": "none"
          },
          {
            "name": "annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "903c6ae0-f0b8-47a0-9c02-07522f4b5770",
            "sourceColumn": "annee",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "71aab4f4-a4d8-4062-8263-ca167f2c1086",
        "measures": [
          {
            "name": "Title_Marge",
            "expression": "\"Etat des marges pharmacies en \"& YEAR(TODAY())",
            "lineageTag": "50fa74fc-5f5b-4eec-af5a-e6b7f91d72f0"
          },
          {
            "name": "Vente_",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(V_Marge[Vente])",
            "formatString": "#,0",
            "lineageTag": "80e99393-e979-4dca-9ee5-780846e84d66"
          },
          {
            "name": "Quantité",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(V_Marge[quantite])",
            "formatString": "#,0",
            "lineageTag": "652b3b1c-3025-4ccb-827d-18a8451151eb"
          },
          {
            "name": "Achat_",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(V_Marge[Achat])",
            "formatString": "#,0",
            "lineageTag": "978dc05e-9021-49f7-9a6a-0a33bdae7617"
          },
          {
            "name": "Marge",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Vente_]-[Achat_]",
            "formatString": "#,0",
            "lineageTag": "a955aee5-010c-4b9b-8fb9-107154818730"
          },
          {
            "name": "%",
            "expression": "V_Marge[Marge]/[Achat_]",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "3c7007ac-9a76-4a9e-a4d9-60ffe3097f83"
          }
        ],
        "partitions": [
          {
            "name": "V_Marge",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_V_Marge = Source{[Schema=\"dbo\",Item=\"V_Marge\"]}[Data],",
                "    #\"Colonnes renommées\" = Table.RenameColumns(dbo_V_Marge,{{\"dim\", \"Désignation\"}})",
                "in",
                "    #\"Colonnes renommées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "reporting PEC_Expedition",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EtaCli",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ca9a76f-48b3-4e7e-99ae-e2798f60f8cd",
            "sourceColumn": "EtaCli",
            "summarizeBy": "none"
          },
          {
            "name": "Eta_Recouv",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5e78a5f-0fc1-4662-bdcd-df4b8c6525ba",
            "sourceColumn": "Eta_Recouv",
            "summarizeBy": "none"
          },
          {
            "name": "NumDoss",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddcbc19e-6ab8-4107-9b93-13e927dd73a0",
            "sourceColumn": "NumDoss",
            "summarizeBy": "none"
          },
          {
            "name": "NumFac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ffdcad8-eed1-43fc-a66a-acc8ffb79601",
            "sourceColumn": "NumFac",
            "summarizeBy": "none"
          },
          {
            "name": "NumPiece",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7dd3ce0f-5cf3-4fc6-b935-e0363410e727",
            "sourceColumn": "NumPiece",
            "summarizeBy": "none"
          },
          {
            "name": "TypFac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09a46252-e2c5-408d-9be7-5d80794e7ff7",
            "sourceColumn": "TypFac",
            "summarizeBy": "none"
          },
          {
            "name": "DatFac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "01663887-5fe4-440f-ae5b-e3b0ce8d2300",
            "sourceColumn": "DatFac",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2184aada-f849-4f69-9b2e-3face548d3fd"
                },
                "isDefault": true,
                "relationship": "a796c01d-64dd-4f6f-aefa-9f40e8db2619"
              }
            ]
          },
          {
            "name": "MntCli",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed3c7a8d-00ae-475b-b9a3-584842ff1df8",
            "sourceColumn": "MntCli",
            "summarizeBy": "sum"
          },
          {
            "name": "MntHO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "13faacc2-dedf-4a10-a261-3c6dda5e71bd",
            "sourceColumn": "MntHO",
            "summarizeBy": "sum"
          },
          {
            "name": "MntPrest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "176ef923-5ca5-43fb-85bd-1bf5708bded1",
            "sourceColumn": "MntPrest",
            "summarizeBy": "sum"
          },
          {
            "name": "MntTVA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "12edd4cc-7a02-4afc-b039-e588a7fe4007",
            "sourceColumn": "MntTVA",
            "summarizeBy": "sum"
          },
          {
            "name": "MntCliPEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c99364c8-d9cf-4e86-85fc-d6147e108b28",
            "sourceColumn": "MntCliPEC",
            "summarizeBy": "sum"
          },
          {
            "name": "MntHOPEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82b88d1b-9df4-49cd-b69f-e0cb8a9b81e4",
            "sourceColumn": "MntHOPEC",
            "summarizeBy": "sum"
          },
          {
            "name": "MntPrestPEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "864c22d7-a991-4b9c-8042-297109d8e2e8",
            "sourceColumn": "MntPrestPEC",
            "summarizeBy": "sum"
          },
          {
            "name": "MntRem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d00355f-d8fb-4f51-98dd-3455e9da3998",
            "sourceColumn": "MntRem",
            "summarizeBy": "sum"
          },
          {
            "name": "MntRecuCl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7c0fcf28-5ac8-48d1-98e4-87ee004c68e6",
            "sourceColumn": "MntRecuCl",
            "summarizeBy": "sum"
          },
          {
            "name": "MntRecuPEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "043cc3ed-48ff-4bb1-9e18-03b76457a5bf",
            "sourceColumn": "MntRecuPEC",
            "summarizeBy": "sum"
          },
          {
            "name": "MntRetenu",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4d4a6ca6-11ed-4600-b82f-04d0c5eca764",
            "sourceColumn": "MntRetenu",
            "summarizeBy": "sum"
          },
          {
            "name": "codtypForfait",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20f182bd-91e4-4ca2-a08b-faee6d04f0ec",
            "sourceColumn": "codtypForfait",
            "summarizeBy": "none"
          },
          {
            "name": "nature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "441e22d5-ed8e-45d2-bdb9-929b6dd427ed",
            "sourceColumn": "nature",
            "summarizeBy": "none"
          },
          {
            "name": "code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49e33a7c-9a86-43bc-aa59-6e6a2c09648a",
            "sourceColumn": "code",
            "summarizeBy": "sum"
          },
          {
            "name": "Designation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02315043-e81a-4220-9f30-62905bbf4a75",
            "sourceColumn": "Designation",
            "summarizeBy": "none"
          },
          {
            "name": "mnt_caution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2af6e191-c8f8-4876-938c-53d50780027c",
            "sourceColumn": "mnt_caution",
            "summarizeBy": "sum"
          },
          {
            "name": "mnt_recu_patient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c84445ff-f729-4d53-a8d5-7ed279eb2497",
            "sourceColumn": "mnt_recu_patient",
            "summarizeBy": "sum"
          },
          {
            "name": "mnt_recu_pec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56a8f20c-2b49-4360-af30-dacc866f857a",
            "sourceColumn": "mnt_recu_pec",
            "summarizeBy": "sum"
          },
          {
            "name": "DesSoc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34986bdb-aa64-4c3d-9358-1c37c83b8a23",
            "sourceColumn": "DesSoc",
            "summarizeBy": "none"
          },
          {
            "name": "numDevis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d61da6f5-3c82-4fef-bbf3-159da131fcce",
            "sourceColumn": "numDevis",
            "summarizeBy": "none"
          },
          {
            "name": "NomCli",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4bc998a-e7fa-4382-b5ae-02bab59f1ec7",
            "sourceColumn": "NomCli",
            "summarizeBy": "none"
          },
          {
            "name": "EtatDevis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3242d131-353c-474d-be87-ecfba5d2580c",
            "sourceColumn": "EtatDevis",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalPEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2b745ec-2be1-47ce-9f63-42258e3d51e9",
            "sourceColumn": "TotalPEC",
            "summarizeBy": "sum"
          },
          {
            "name": "NumSoc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79fba9ce-392d-449d-ae3e-0b405e085819",
            "sourceColumn": "NumSoc",
            "summarizeBy": "none"
          },
          {
            "name": "DesignationM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92a2dd66-c9cd-4bd7-9419-27d97eaa9129",
            "sourceColumn": "DesignationM",
            "summarizeBy": "none"
          },
          {
            "name": "NumSocMutuelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47042bf4-a59e-4102-9dcf-82c78949073b",
            "sourceColumn": "NumSocMutuelle",
            "summarizeBy": "none"
          },
          {
            "name": "TVAPEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4be16a54-d30d-4222-95a6-fc2021cc68e3",
            "sourceColumn": "TVAPEC",
            "summarizeBy": "sum"
          },
          {
            "name": "PAYER_test",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "05f3afa4-d699-4947-b389-04a7167e4beb",
            "sourceColumn": "PAYER_test",
            "summarizeBy": "sum"
          },
          {
            "name": "DatEnvoi",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ecf71f78-0558-45c5-a90a-dc3397e51b89",
            "sourceColumn": "DatEnvoi",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5a44dc05-5a38-44b2-943f-380f666a1aca"
                },
                "isDefault": true,
                "relationship": "d282e541-fd49-476d-953c-0e0a19df3aef"
              }
            ]
          },
          {
            "name": "doss_avoir_Tot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c3d1604a-3c0e-4bf4-ba79-dd7ef7fde7f5",
            "sourceColumn": "doss_avoir_Tot",
            "summarizeBy": "sum"
          },
          {
            "name": "doss_avoir_Tot_Ex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53b4e2b8-31eb-4c5f-a930-7adf26219691",
            "sourceColumn": "doss_avoir_Tot_Ex",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8575fc46-8392-4d0b-b09e-ed55b752fb9c",
        "measures": [
          {
            "name": "part honoraire pec expédié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]=\"E\", 'reporting PEC_Expedition'[doss_avoir_Tot_Ex]=1) ",
            "formatString": "#,0",
            "lineageTag": "4625622a-7505-4a64-b478-974077d39c68"
          },
          {
            "name": "Solde patient expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate([total facture TM]-[Total réglé TM],'reporting PEC_Expedition'[Eta_Recouv]=\"E\")",
            "formatString": "#,0",
            "lineageTag": "6d66ceac-603e-4921-aeb9-8df918b0a2be"
          },
          {
            "name": "Solde PEC expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate([total facture PEC]-[Total réglé PEC],'reporting PEC_Expedition'[Eta_Recouv]=\"E\")",
            "formatString": "#,0",
            "lineageTag": "1ac281d1-91c4-4fae-8754-d61ed2ff6f42"
          },
          {
            "name": "Total réglé PEC expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_pec]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\", 'reporting PEC_Expedition'[Eta_Recouv]=\"E\", 'reporting PEC_Expedition'[doss_avoir_Tot_Ex]=1) ",
            "formatString": "#,0",
            "lineageTag": "fadf12b8-2202-44a6-b438-85aed23df00f"
          },
          {
            "name": "Total réglé TM expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_patient]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]=\"E\") ",
            "formatString": "#,0",
            "lineageTag": "dd594890-f403-45ae-9acf-4959abf0de3d"
          },
          {
            "name": "part clinique PEC non expédié",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[TVAPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]<>\"E\",'reporting PEC_Expedition'[doss_avoir_Tot]=1) ",
            "formatString": "#,0",
            "lineageTag": "661e5a25-437b-47eb-8f07-3846de8c6c5a"
          },
          {
            "name": "part honoraire pec non expédié",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]<>\"E\",'reporting PEC_Expedition'[doss_avoir_Tot]=1) ",
            "formatString": "#,0",
            "lineageTag": "b3bf12f9-82ba-4641-9f15-85bb4f09dd5b"
          },
          {
            "name": "total facture TM expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]-'reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[MntHO]-'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrest]-'reporting PEC_Expedition'[MntPrestPEC]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]=\"E\")",
            "formatString": "#,0",
            "lineageTag": "ec997de0-e1ee-474c-aee4-2dc23ba81600"
          },
          {
            "name": "total facture PEC expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]+'reporting PEC_Expedition'[TVAPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]=\"E\", 'reporting PEC_Expedition'[doss_avoir_Tot_Ex]=1)",
              " "
            ],
            "formatString": "#,0",
            "lineageTag": "1d582935-2291-4b35-8e75-de6c5816fcd9"
          },
          {
            "name": "Total_PEC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM('reporting PEC_Expedition'[TotalPEC])",
            "lineageTag": "4f12ec7f-06a6-4eef-89ad-d6a6fe7e17f5"
          },
          {
            "name": "part clinique PEC expédié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[TVAPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]=\"E\", 'reporting PEC_Expedition'[doss_avoir_Tot_Ex]=1) ",
            "formatString": "#,0",
            "lineageTag": "1488ac31-17fd-4edc-a1c8-5d9ac3958fa4"
          },
          {
            "name": "total facture PEC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]+'reporting PEC_Expedition'[TVAPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "0fa563b7-505e-4be0-8333-1818a041abd1"
          },
          {
            "name": "Total réglé PEC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_pec]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "45197136-ced4-401a-839d-5ef817c64aef"
          },
          {
            "name": "total facture TM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]-'reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[MntHO]-'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrest]-'reporting PEC_Expedition'[MntPrestPEC]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "c0f58a1a-b861-4269-a553-710d446b4daf"
          },
          {
            "name": "Total réglé TM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_patient]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "b102ce0b-d835-490f-8ded-fc95c83625ed"
          },
          {
            "name": "facture total Payant avec mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]+'reporting PEC_Expedition'[MntHO]+'reporting PEC_Expedition'[MntPrest]),filter('reporting PEC_Expedition','reporting PEC_Expedition'[NumSoc]=\"\" && 'reporting PEC_Expedition'[NumSocMutuelle]<>\"\" && 'reporting PEC_Expedition'[EtaCli]=\"1\"))",
            "lineageTag": "94d4422a-5058-4082-a19c-730f6aee9887"
          },
          {
            "name": "facture total Payant sans mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]+'reporting PEC_Expedition'[MntHO]+'reporting PEC_Expedition'[MntPrest]),'reporting PEC_Expedition'[NumSoc]=\"\",'reporting PEC_Expedition'[NumSocMutuelle]=\"\",'reporting PEC_Expedition'[EtaCli]=\"1\")",
            "lineageTag": "ecbddf44-4956-4c36-b36c-f42461572bd7"
          },
          {
            "name": "mnt caution avec mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum('reporting PEC_Expedition'[mnt_caution]),filter('reporting PEC_Expedition','reporting PEC_Expedition'[NumSoc]=\"\" && 'reporting PEC_Expedition'[NumSocMutuelle]<>\"\" && 'reporting PEC_Expedition'[EtaCli]=\"1\"))",
            "lineageTag": "c6bd25f6-9fa5-4158-a4da-dd14a7c31813"
          },
          {
            "name": "mnt caution pec",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum('reporting PEC_Expedition'[mnt_caution]),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[NumSoc]<>\"\") ",
            "lineageTag": "4f14f193-7c1e-4103-b3b2-2b621e512900"
          },
          {
            "name": "mnt caution sans mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum('reporting PEC_Expedition'[mnt_caution]),'reporting PEC_Expedition'[NumSoc]=\"\",'reporting PEC_Expedition'[NumSocMutuelle]=\"\",'reporting PEC_Expedition'[EtaCli]=\"1\")",
            "lineageTag": "36969798-61e2-425b-9e91-a71c3210b5ec"
          },
          {
            "name": "mnt caution TM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum('reporting PEC_Expedition'[mnt_caution]))-([mnt caution avec mutuelle]+[mnt caution sans mutuelle]+[mnt caution pec])",
            "lineageTag": "c4e79981-f4da-40e4-925b-b926b447fbc0"
          },
          {
            "name": "Montant caution",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum('reporting PEC_Expedition'[mnt_caution]),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[NumSoc]<>\"\")",
            "lineageTag": "410ba171-6260-4dda-bb54-1021c19eea91"
          },
          {
            "name": "part clinique PEC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[TVAPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "e1d20f77-6679-4e16-bf30-14876fa4fe0a"
          },
          {
            "name": "part honoraire",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "b254ab00-b5d5-4a4e-8fab-5c5b5dd17d3b"
          },
          {
            "name": "part honoraire pec",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "7808402a-5cfd-470e-8dbe-26766f54bc9b"
          },
          {
            "name": "part clinique TM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]-'reporting PEC_Expedition'[MntCliPEC]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "7453a584-7a1f-4a74-95ad-28ac64506af7"
          },
          {
            "name": "part honoraire TM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHO]-'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrest]-'reporting PEC_Expedition'[MntPrestPEC]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\") ",
            "lineageTag": "453e1614-acc5-4171-ae3f-43977d54adb6"
          },
          {
            "name": "Solde PEC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([total facture PEC]-[Total réglé PEC] )",
            "lineageTag": "256a234d-2c64-443e-a374-1e832f4bfe81"
          },
          {
            "name": "Solde TM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[total facture TM]-[Total réglé TM]",
            "lineageTag": "107028e6-5d17-41af-af57-ff71a69b50b9"
          },
          {
            "name": "part clinique Payant sans mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]),'reporting PEC_Expedition'[NumSoc]=\"\",'reporting PEC_Expedition'[NumSocMutuelle]=\"\",'reporting PEC_Expedition'[EtaCli]=\"1\")",
            "formatString": "#,0",
            "lineageTag": "3b46592f-1ba3-4cba-914a-74568430836c"
          },
          {
            "name": "part honoraire Payant sans mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHO]+'reporting PEC_Expedition'[MntPrest]),'reporting PEC_Expedition'[NumSoc]=\"\",'reporting PEC_Expedition'[NumSocMutuelle]=\"\",'reporting PEC_Expedition'[EtaCli]=\"1\")",
            "lineageTag": "aa1fd338-8647-4a1c-b3a7-67116ce2242a"
          },
          {
            "name": "total reglé payant sans mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_pec]+'reporting PEC_Expedition'[mnt_recu_patient]),'reporting PEC_Expedition'[NumSoc]=\"\",'reporting PEC_Expedition'[NumSocMutuelle]=\"\",'reporting PEC_Expedition'[EtaCli]=\"1\")",
            "lineageTag": "5108993b-8216-4430-9f66-07ebe9a420b8"
          },
          {
            "name": "part clinique Payant avec mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]),filter('reporting PEC_Expedition','reporting PEC_Expedition'[NumSoc]=\"\" && 'reporting PEC_Expedition'[NumSocMutuelle]<>\"\" && 'reporting PEC_Expedition'[EtaCli]=\"1\"))",
            "lineageTag": "0b0fc650-d7eb-43a2-8d3c-ecd0cd2d1b53"
          },
          {
            "name": "part honoraire Payant avec mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntHO]+'reporting PEC_Expedition'[MntPrest]),filter('reporting PEC_Expedition','reporting PEC_Expedition'[NumSoc]=\"\" && 'reporting PEC_Expedition'[NumSocMutuelle]<>\"\" && 'reporting PEC_Expedition'[EtaCli]=\"1\"))",
            "lineageTag": "915998b6-b225-4486-986f-cf3bb34abe80"
          },
          {
            "name": "total reglé payant avec mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_pec]+'reporting PEC_Expedition'[mnt_recu_patient]),'reporting PEC_Expedition'[NumSoc]=\"\",'reporting PEC_Expedition'[NumSocMutuelle]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\")",
            "lineageTag": "e8d6195e-e7f6-437f-b26c-09991397cfdc"
          },
          {
            "name": "solde sans mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate ([facture total Payant sans mutuelle]-[total reglé payant sans mutuelle])",
            "lineageTag": "fa694d3a-ee00-42f4-b333-fdbee34c50b3"
          },
          {
            "name": "solde avec mutuelle",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate([facture total Payant avec mutuelle]-[total reglé payant avec mutuelle])",
            "lineageTag": "f374b283-8c47-40a6-99c3-dcbb08de5d78"
          },
          {
            "name": "total facture PEC non expedié",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrestPEC]+'reporting PEC_Expedition'[TVAPEC]),not(ISBLANK('reporting PEC_Expedition'[NumSoc])),'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]<>\"E\",'reporting PEC_Expedition'[doss_avoir_Tot]=1) ",
            "formatString": "#,0",
            "lineageTag": "f431140b-f1eb-497f-b2f4-c5ef97c4b826"
          },
          {
            "name": "total facture TM non expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[MntCli]-'reporting PEC_Expedition'[MntCliPEC]+'reporting PEC_Expedition'[MntHO]-'reporting PEC_Expedition'[MntHOPEC]+'reporting PEC_Expedition'[MntPrest]-'reporting PEC_Expedition'[MntPrestPEC]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]<>\"E\")",
            "formatString": "#,0",
            "lineageTag": "81e9c085-f68b-43c2-80de-5ed634420f7d"
          },
          {
            "name": "Total réglé PEC non expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_pec]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\", 'reporting PEC_Expedition'[Eta_Recouv]<>\"E\") ",
            "lineageTag": "1e754ff4-ddab-4aeb-a160-12749ea80dc0"
          },
          {
            "name": "Solde PEC non expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate([total facture PEC non expedié]-[Total réglé PEC non expedié])",
            "formatString": "#,0",
            "lineageTag": "3de3d7d5-2713-48da-aa4d-e0460006ca12"
          },
          {
            "name": "Total réglé TM non expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate(sumx('reporting PEC_Expedition','reporting PEC_Expedition'[mnt_recu_patient]),'reporting PEC_Expedition'[NumSoc]<>\"\",'reporting PEC_Expedition'[EtaCli]=\"1\",'reporting PEC_Expedition'[Eta_Recouv]<>\"E\") ",
            "formatString": "#,0",
            "lineageTag": "a5ea8335-a4b7-43a3-a359-76079d7bd60f"
          },
          {
            "name": "Solde patient non expedié",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "calculate([total facture TM]-[Total réglé TM],'reporting PEC_Expedition'[Eta_Recouv]<>\"E\")",
            "formatString": "#,0",
            "lineageTag": "82d3d755-11c2-4256-8000-ed8a3df0bb00"
          }
        ],
        "partitions": [
          {
            "name": "reporting PEC_Expedition-ad3cd394-3077-429f-9c5c-5acf4b5b9016",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_Vreporting_PEC_Expedition = Source{[Schema=\"dbo\",Item=\"Vreporting_PEC_Expedition\"]}[Data]",
                "in",
                "    dbo_Vreporting_PEC_Expedition"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2184aada-f849-4f69-9b2e-3face548d3fd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "87602d98-06af-4cd2-8416-39c098c2ea02",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d34d8189-fb28-43b9-9de5-3582dfa9412f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "adb93c44-11a3-4207-a35c-420435df01d5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f292bea5-0b86-4886-bd7c-5058220d1aba",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c904e17d-0f63-4607-bf3a-8ec6970ddd5f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c4879939-9931-4fa3-8879-4e02ee1f7757",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bb32f9ae-4466-401a-9307-a4234c71fb3e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "93d25afd-5eb6-4684-8b43-e94911c8be77",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d7fb2865-5975-4909-a76e-9e4c108fae26",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d06b9f84-cc42-4129-a9ab-fc76939de1e3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "557d08ba-5468-4e1c-8024-8af54a05e1b7",
                "ordinal": 3
              }
            ],
            "lineageTag": "597c4235-a1f4-4a7e-afb4-6aaae524c2fb"
          }
        ],
        "isHidden": true,
        "lineageTag": "86337a16-ef8d-43a5-8ffe-96b5d12dd1b6",
        "partitions": [
          {
            "name": "LocalDateTable_2184aada-f849-4f69-9b2e-3face548d3fd-2d5d1beb-90c5-4a4f-8e63-f2787b281d56",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('reporting PEC_Expedition'[DatFac])), 1, 1), Date(Year(MAX('reporting PEC_Expedition'[DatFac])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "recouvrement",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f892a2424289428b91bed0b43a70feb4"
          }
        ],
        "columns": [
          {
            "name": "DatFac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6ffe6b47-8182-4836-a79c-11e9ec7443f4",
            "sourceColumn": "reporting PEC_Expedition[DatFac]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bca547ae-0462-46ef-b15b-d3fdd8c08999"
                },
                "isDefault": true,
                "relationship": "f761c637-de3e-41e2-ace7-0fc1e0862b12"
              }
            ]
          },
          {
            "name": "montant caution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0aea3c42-2a1a-4356-9db3-198baac33f11",
            "sourceColumn": "[montant caution]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "nature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "32a619d2-3ab3-4c83-ba00-4979f8cb49e2",
            "sourceColumn": "[nature]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Total facture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aaf0b5bb-299e-4b8d-b244-07ea53e23088",
            "sourceColumn": "[Total facture]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "part clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d8241008-57f5-4a96-a4f5-effc561dee56",
            "sourceColumn": "[part clinique]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "part honoraire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "35c933ce-dbc4-4a6e-b6a4-c0a3ded4ec24",
            "sourceColumn": "[part honoraire]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "total réglé",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7d4f8771-64da-4aeb-a92d-d8e5c6f821c5",
            "sourceColumn": "[total réglé]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "solde",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b6d87b9b-b0d9-4425-8970-5662b42fd80f",
            "sourceColumn": "[solde]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "93f5a9f2-2ddc-4dad-ab89-5c7cacff24a8",
        "measures": [
          {
            "name": "caution",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(recouvrement[montant caution])",
            "lineageTag": "65d9c5f6-5ba4-4e52-befc-0228b376e01b"
          },
          {
            "name": "part_clinique",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(recouvrement[part clinique])",
            "lineageTag": "a7293645-1170-49b9-a5db-e1378ce74488"
          },
          {
            "name": "tot_fact",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "sum(recouvrement[Total facture]) ",
              "--total des facture partie pec payé et non payé"
            ],
            "lineageTag": "bb1d10dd-969f-4088-a98f-589c33b36b23"
          },
          {
            "name": "part_honoraire",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(recouvrement[part honoraire])",
            "lineageTag": "180480c3-f38d-4f19-9a41-eec52fca2cf9"
          },
          {
            "name": "total_reglé",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(recouvrement[total réglé])",
            "lineageTag": "767e7a3a-c615-4b8e-b69e-ce4e49bd51b6"
          },
          {
            "name": "total_solde",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum(recouvrement[solde]) ",
            "lineageTag": "24fc5a9d-1d88-4790-93f8-282334efccf4"
          }
        ],
        "partitions": [
          {
            "name": "recouvrement-a9245363-58b1-4c8a-a909-5ecbd402bb6d",
            "mode": "import",
            "source": {
              "expression": [
                "var x1=SUMMARIZE('reporting PEC_Expedition','reporting PEC_Expedition'[DatFac],\"montant caution\",[mnt caution pec],\"nature\",\"PEC\",\"Total facture\",'reporting PEC_Expedition'[total facture PEC],\"part clinique\",[part clinique pec],\"part honoraire\",[part honoraire pec],\"total réglé\",[Total réglé PEC],\"solde\",[Solde PEC])",
                "var x2=SUMMARIZE('reporting PEC_Expedition','reporting PEC_Expedition'[DatFac],\"montant caution\",[mnt caution TM],\"nature\",\"TM\",\"Total facture\",'reporting PEC_Expedition'[total facture TM],\"part clinique\",[part clinique TM],\"part honoraire\",[part honoraire TM],\"total réglé\",[Total réglé TM],\"solde\",[Solde TM])",
                "var x3=SUMMARIZE('reporting PEC_Expedition','reporting PEC_Expedition'[DatFac],\"montant caution\",[mnt caution sans mutuelle],\"nature\",\"Payant sans mutuelle\",\"Total facture\",'reporting PEC_Expedition'[facture total Payant sans mutuelle],\"part clinique\",[part clinique Payant sans mutuelle],\"part honoraire\",[part honoraire Payant sans mutuelle],\"total réglé\",[total reglé payant sans mutuelle],\"solde\",[solde sans mutuelle])",
                "var x4=SUMMARIZE('reporting PEC_Expedition','reporting PEC_Expedition'[DatFac],\"montant caution\",[mnt caution avec mutuelle],\"nature\",\"Payant avec mutuelle\",\"Total facture\",'reporting PEC_Expedition'[facture total Payant avec mutuelle],\"part clinique\",[part clinique Payant avec mutuelle],\"part honoraire\",[part honoraire Payant avec mutuelle],\"total réglé\",[total reglé payant avec mutuelle],\"solde\",[solde avec mutuelle])",
                "return union(x1,x2,x3,x4)"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "VhospitaliseJour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "qte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4df86c62-974e-4238-b931-ba34bb299e88",
            "sourceColumn": "qte",
            "summarizeBy": "sum"
          },
          {
            "name": "pec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "566c92a1-d916-436b-a759-3fde7adb0add",
            "sourceColumn": "pec",
            "summarizeBy": "sum"
          },
          {
            "name": "payant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "844564cb-033f-49ae-b02e-63164b983d9e",
            "sourceColumn": "payant",
            "summarizeBy": "sum"
          },
          {
            "name": "des",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fae0a8c-226e-465a-a0c2-e7fcd3705507",
            "sourceColumn": "des",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "909b0f00-eb02-452e-8579-cc5ef1eadcae",
        "measures": [
          {
            "name": "qty",
            "expression": "SUM(VhospitaliseJour[qte])",
            "formatString": "0",
            "lineageTag": "60544301-545f-417f-99c1-a2e1ca75383a"
          }
        ],
        "partitions": [
          {
            "name": "VhospitaliseJour",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VhospitaliseJour = Source{[Schema=\"dbo\",Item=\"VhospitaliseJour\"]}[Data]",
                "in",
                "    dbo_VhospitaliseJour"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bca547ae-0462-46ef-b15b-d3fdd8c08999",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d232cfac-bd0b-4519-8624-d61298e13870",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2cfc6b6b-d287-4b63-addc-eda9c3ad2e2f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8005dfc6-d607-47a7-8903-67bfc45e2fee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5b33f9a2-0578-49e7-90cd-8b7c63f6338f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "69289207-e374-45a2-b625-9ebc893f50cb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b5038933-7e44-43da-9181-3a369a9f6ef7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "552b3cc8-28ad-4951-8715-31cecf9bc5f3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "efe63879-b853-4aec-96c4-1d2bc392c86d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "512713fa-3c4e-42cc-9038-5b03cbd7af16",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e83f1600-7ae0-4fab-a571-583184f3cec6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "daa89146-58ee-4fef-a042-937b1a4eacf2",
                "ordinal": 3
              }
            ],
            "lineageTag": "45fb522f-d746-4d1a-a2e8-2b48dcdc7e8d"
          }
        ],
        "isHidden": true,
        "lineageTag": "d2d8ae4c-c59a-42a2-b397-79aeb2bc2f3c",
        "partitions": [
          {
            "name": "LocalDateTable_bca547ae-0462-46ef-b15b-d3fdd8c08999",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('recouvrement'[DatFac])), 1, 1), Date(Year(MAX('recouvrement'[DatFac])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "v_occupation_bloc",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DureeOp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e34dab43-559a-48a4-bce6-c0f8d03cc971",
            "sourceColumn": "DureeOp",
            "summarizeBy": "sum"
          },
          {
            "name": "jrs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca0b1fff-e44c-4ad9-8245-f0b767cebf8d",
            "sourceColumn": "jrs",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ca8c26ae-03d0-4611-9327-26264ad01be1",
        "measures": [
          {
            "name": "occup",
            "expression": "sum(v_occupation_bloc[DureeOp]) ",
            "formatString": "0",
            "lineageTag": "6bca55bd-a693-4eee-9041-53279f6e6a0d"
          }
        ],
        "partitions": [
          {
            "name": "v_occupation_bloc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_v_occupation_bloc = Source{[Schema=\"dbo\",Item=\"v_occupation_bloc\"]}[Data]",
                "in",
                "    dbo_v_occupation_bloc"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_69ee96d6-e8f8-4333-a0f0-ef23fbc1a166",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "276f9d42-541c-406e-a456-a8d5b79eb68d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cfff2402-a027-45bd-8d0e-fd1db2783bc3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "29caba26-e957-44cb-b3ac-146a823de1ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8a3b117a-627f-4fcf-a228-7a4c6304cc14",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "dd05981e-f57b-4dab-a2b3-0fee26b708cd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "abacb199-75ea-43d2-a593-64597d151348",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c9802bc1-bec9-4d3d-a02c-ba9d1790d5c6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0a0fd179-0b97-4e12-b281-eb857261124b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3e7d04bd-0647-471b-838f-56cc7a4ccd42",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e546d424-252f-4dc1-a57b-b33036eed68e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a27aba4-e00e-45ba-87e8-6e98c236053a",
                "ordinal": 3
              }
            ],
            "lineageTag": "a40cce9f-6f19-4e4d-8bed-5f5bbb7c2566"
          }
        ],
        "isHidden": true,
        "lineageTag": "a9691dac-9824-47e2-875d-352f6270f0a4",
        "partitions": [
          {
            "name": "LocalDateTable_69ee96d6-e8f8-4333-a0f0-ef23fbc1a166",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Vurgence'[DatArr])), 1, 1), Date(Year(MAX('Vurgence'[DatArr])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Mesure_BlockHeure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "0883fd75-5c39-4415-9748-c23c0660eab4",
        "measures": [
          {
            "name": "totalMM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "var a=",
              "            IF([Sum MM] >=1",
              "            ,[MM_]-(INT([Sum MM])*60)",
              "            ,[MM_])",
              "            RETURN FLOOR(ROUND(a,0),1)"
            ],
            "formatString": "0",
            "lineageTag": "4e5c4a3c-6d2e-4a3f-bd84-56da7af06344"
          },
          {
            "name": "totalH",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "IF([Sum MM] >=1,FLOOR([Sum MM],1)+[Sum H],[Sum H])",
            "formatString": "0",
            "lineageTag": "d9a2ecf8-40fb-42ab-bc6a-e951f0da1515"
          },
          {
            "name": "Total Heure",
            "expression": "[totalH]& \":\" & [totalMM]& \" h\"",
            "lineageTag": "a90f8755-045d-4036-aa63-f436719e6bbf"
          },
          {
            "name": "Sum MM",
            "expression": [
              "Var MM=[MM_]",
              "RETURN MM/60"
            ],
            "formatString": "0.00",
            "lineageTag": "40b3221e-b63a-411a-ac57-4316f6797dbc"
          },
          {
            "name": "Sum H",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(BlocsHeure[HH])",
            "lineageTag": "63bf4c66-f454-4782-b136-76459815cffc"
          },
          {
            "name": "Nombre de salle",
            "expression": "COUNT(BlocsHeure[salle])",
            "formatString": "0",
            "lineageTag": "c0580802-5ee5-4341-8305-666e9294457a"
          },
          {
            "name": "Nb h",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "Sum(BlocsHeure[duree])/60",
            "lineageTag": "463d0934-c408-45fa-8fa0-c89a745dbed9"
          },
          {
            "name": "MM_",
            "expression": "SUM(BlocsHeure[MM])",
            "formatString": "0",
            "lineageTag": "1a547968-6694-47c1-81b8-cb4beb0faa63"
          },
          {
            "name": "% bloc",
            "expression": "SUM(BlocsHeure[duree])/([Nombre de salle]*720)",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "f7308b84-eab9-4841-93f8-3e9c85f9c30d"
          },
          {
            "name": "Total H",
            "expression": "[totalH] &  \" H\"",
            "lineageTag": "7c347815-8754-4f0e-9265-5594dad51be9"
          }
        ],
        "partitions": [
          {
            "name": "Mesure_BlockHeure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BlocsHeure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Row",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85c92bf3-5362-4dfb-88aa-18ae92e74a30",
            "sourceColumn": "Row",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "salle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3092087e-446f-4a51-80d8-9ea70674329d",
            "sourceColumn": "salle",
            "sourceProviderType": "nvarchar(5)",
            "summarizeBy": "none"
          },
          {
            "name": "inoccupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c52ecebd-a7dc-4309-a8ca-232e71ef9619",
            "sourceColumn": "inoccupation",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "duree",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14314ded-451e-4bc7-b664-ba9f037707c4",
            "sourceColumn": "duree",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Date_Reservation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2f401327-391b-4229-bb79-449ce78dde0a",
            "sourceColumn": "Date_Reservation",
            "sourceProviderType": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_17f3f2ef-7b30-43f3-bce4-4fa188a4e931"
                },
                "isDefault": true,
                "relationship": "c6e4bf07-8d03-4cb0-9f5d-cc01748a3853"
              }
            ]
          },
          {
            "name": "Num_Bloc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "80233709-439b-475d-8da0-78734b12f274",
            "sourceColumn": "Num_Bloc",
            "sourceProviderType": "nvarchar(2)",
            "summarizeBy": "none"
          },
          {
            "name": "DureeOp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1848fd44-be71-4840-8312-2222f23e3a49",
            "sourceColumn": "DureeOp",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "HH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "552433f4-c208-4c63-b6d6-6a691d26583e",
            "sourceColumn": "HH",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          },
          {
            "name": "heure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "a4f7b5ee-e8d7-4295-bb7d-29f4c25bf0f5",
            "sourceColumn": "heure",
            "sourceProviderType": "varchar(13)",
            "summarizeBy": "none"
          },
          {
            "name": "LibBloc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecc3d69b-d4ac-4a26-8e05-54df8aa7911e",
            "sourceColumn": "LibBloc",
            "sourceProviderType": "nvarchar(25)",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "f4fba67b-c3aa-4622-bd49-8b278944df6f",
            "sourceColumn": "Occupation",
            "sourceProviderType": "decimal(33, 23)",
            "summarizeBy": "sum"
          },
          {
            "name": "MM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9ce02bcd-5634-424f-9a98-6cde8c715631",
            "sourceColumn": "MM",
            "sourceProviderType": "float",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "668795fe-8cfb-443d-a97a-2e57b55b4e57",
        "partitions": [
          {
            "name": "BlocsHeure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_BlocsHeure = Source{[Schema=\"dbo\",Item=\"BlocsHeure\"]}[Data]",
                "in",
                "    dbo_BlocsHeure"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VRecouvrement",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "NumSoc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c827417-96bc-4827-b5b5-8dbd16db6566",
            "sourceColumn": "NumSoc",
            "summarizeBy": "none"
          },
          {
            "name": "libSoc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bc81cf3-537b-4b4f-aa7e-a50569dc2e88",
            "sourceColumn": "libSoc",
            "summarizeBy": "none"
          },
          {
            "name": "Solde factures impayées",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3ef5dd3-69fe-4529-847a-fbf376adee80",
            "sourceColumn": "Solde factures impayées",
            "summarizeBy": "sum"
          },
          {
            "name": "Avance non apurée",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82feff19-ab65-4b61-a7f0-fe67a3771991",
            "sourceColumn": "Avance non apurée",
            "summarizeBy": "sum"
          },
          {
            "name": "Les encours hospitalisées",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcd70084-f0c5-464f-b096-f881c066502c",
            "sourceColumn": "Les encours hospitalisées",
            "summarizeBy": "sum"
          },
          {
            "name": "Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1250a4bb-5e3f-443e-afdd-c5a4324a7d88",
            "sourceColumn": "Total",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "69909718-20fa-4368-b8f8-0b87e993487a",
        "partitions": [
          {
            "name": "VRecouvrement",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VRecouvrement = Source{[Schema=\"dbo\",Item=\"VRecouvrement\"]}[Data]",
                "in",
                "    dbo_VRecouvrement"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5a44dc05-5a38-44b2-943f-380f666a1aca",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f0604a74-3e79-4446-9912-a729d11c9145",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ce97525b-6545-45d5-8ed9-2532169f6b09",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e50d2898-dc75-41be-8e02-9bd4ba75697e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1bb4c411-773d-420d-bf92-e33961689351",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e38b347b-96bf-40d1-95c1-4bc91cdebc81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ae94e013-7602-4893-ba64-1c3a26d8ba2c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6d97fba7-1108-4187-ab21-994a138b51c5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6084953b-1bf9-4367-8748-6b765ad72941",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "25fee571-81c6-406e-a033-67d3a6786000",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e9f43634-8ff3-4b9a-8c1b-8fa103d8f1dc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "88218dd5-0b3a-4352-9a0c-ade536dab583",
                "ordinal": 3
              }
            ],
            "lineageTag": "7ee78a64-06c3-4451-a687-5959312a8e21"
          }
        ],
        "isHidden": true,
        "lineageTag": "dd698d65-a914-42f4-8090-f4d2ec8b0e20",
        "partitions": [
          {
            "name": "LocalDateTable_5a44dc05-5a38-44b2-943f-380f666a1aca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('reporting PEC_Expedition'[DatEnvoi])), 1, 1), Date(Year(MAX('reporting PEC_Expedition'[DatEnvoi])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VHopital_Jour",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Des",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a15dcfad-056d-4c33-936c-8eb474dc448e",
            "sourceColumn": "Des",
            "summarizeBy": "none"
          },
          {
            "name": "nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "486e0d58-9976-4c42-b081-954d54002d28",
            "sourceColumn": "nbr",
            "summarizeBy": "sum"
          },
          {
            "name": "mnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "695ddd0a-464e-4fed-a029-ffedae82c3df",
            "sourceColumn": "mnt",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8c4f7ed5-3431-4b04-8a4e-a74ca51db8d3",
        "measures": [
          {
            "name": "Hopital_jour",
            "expression": "SUM(VHopital_Jour[nbr])",
            "formatString": "0",
            "lineageTag": "83ce80d1-d686-411f-8be4-bdde66122fbb"
          }
        ],
        "partitions": [
          {
            "name": "VHopital_Jour",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VHopital_Jour = Source{[Schema=\"dbo\",Item=\"VHopital_Jour\"]}[Data]",
                "in",
                "    dbo_VHopital_Jour"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Mesure Achat_Stock",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "430d98b2-d630-4825-affc-74a35e87a9a3",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c1775ce9-b10d-4de3-aba9-a2929a021b47",
        "partitions": [
          {
            "name": "Mesure Achat_Stock",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "V_achat_Stock",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d1425df-30af-43c4-a84e-2862f8737414",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Valeur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd3f3004-07eb-4f66-b751-97a07b6a5b82",
            "sourceColumn": "Valeur",
            "summarizeBy": "sum"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f2f5c54-afee-4611-80ce-8f9ac2eb7377",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Nature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecbe5595-fe9e-4097-9e64-9d39aecc074b",
            "sourceColumn": "Nature",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "545d6142-f57c-4a55-a4c5-50c4c2daf13c",
        "partitions": [
          {
            "name": "V_achat_Stock",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_V_Achat_Stock = Source{[Schema=\"dbo\",Item=\"V_achat_Stock\"]}[Data]",
                "in",
                "    dbo_V_Achat_Stock"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_17f3f2ef-7b30-43f3-bce4-4fa188a4e931",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e3ef46a5-f6d9-42ba-8461-296f74327c89",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ce3e1104-f93e-4c78-bf3f-c331f6aa6236",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "cbc32745-8fab-4ecf-a8c2-364dae67e79c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2ce25a0b-332d-4df7-9712-c87cabc01069",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "28b010e1-5a06-4991-8f4e-95e0d55ca10c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c090846d-6051-4b56-8d03-1fd764580b77",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "cf105641-1bf3-4cdf-b4d7-b690e448ea06",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7330e377-2645-487a-be0a-117fe82a3d1e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6c95f83d-3ef9-4875-9fd0-cacd213626c5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5f648cec-3863-4625-9b7d-0ac6796b8351",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "383851e9-e336-43e0-9a4e-946a9e49c2b7",
                "ordinal": 3
              }
            ],
            "lineageTag": "5a89cdc7-0aea-4509-aa2c-b28a96b2199c"
          }
        ],
        "isHidden": true,
        "lineageTag": "146c4e28-091c-4947-8af9-87555f374cc1",
        "partitions": [
          {
            "name": "LocalDateTable_17f3f2ef-7b30-43f3-bce4-4fa188a4e931",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('BlocsHeure'[Date_Reservation])), 1, 1), Date(Year(MAX('BlocsHeure'[Date_Reservation])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Reporting Prestation_annule",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dossier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea4e5dcb-bf78-4184-ad2c-c90cced9ee4b",
            "sourceColumn": "Dossier",
            "summarizeBy": "none"
          },
          {
            "name": "Utilisateur création",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cac2ddfd-679e-4d93-a2e5-658e353b93ae",
            "sourceColumn": "Utilisateur création",
            "summarizeBy": "none"
          },
          {
            "name": "Utilisateur suppression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f1d3bc5-4122-42db-9716-3d43293a3fa5",
            "sourceColumn": "Utilisateur suppression",
            "summarizeBy": "none"
          },
          {
            "name": "Date suppression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e73b8586-8cb6-4516-820e-9ac02f4324b8",
            "sourceColumn": "Date suppression",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a60faa9b-c25c-40e4-af40-a8c6cf54653f"
                },
                "isDefault": true,
                "relationship": "2c898ca9-61ba-4c9b-8811-adf63950cdde"
              }
            ]
          },
          {
            "name": "Date prestation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c6993e03-797c-4ee7-b2cb-dbfb29ad5448",
            "sourceColumn": "Date prestation",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_08212afe-ece0-4abe-8e80-9e00b104b9f5"
                },
                "isDefault": true,
                "relationship": "b753c6cd-45ab-4c3e-85e0-3db4d09c664b"
              }
            ]
          },
          {
            "name": "Heure prestation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ba1d00ba-2e90-478f-86cf-4f1a200df722",
            "sourceColumn": "Heure prestation",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9e05e250-3c67-4c7c-b0bb-041150b40c55"
                },
                "isDefault": true,
                "relationship": "7fdd00ef-a1a9-42bc-a868-df945c82cafa"
              }
            ]
          },
          {
            "name": "Code prestation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ad2d3d4-ee98-44bf-980f-7d50b745c8fe",
            "sourceColumn": "Code prestation",
            "summarizeBy": "none"
          },
          {
            "name": "Libelle prestation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fda90790-ae97-4a4b-9587-d510d55fd42c",
            "sourceColumn": "Libelle prestation",
            "summarizeBy": "none"
          },
          {
            "name": "Montant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16b17b0a-d59e-43b1-aefb-6b65357aedfb",
            "sourceColumn": "Montant",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0d6e286c-7b8f-4c1a-a426-041643adc006",
        "partitions": [
          {
            "name": "Reporting Prestation_annule",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    Reporting_Prestation_annule = Source{[Schema=\"Reporting\",Item=\"Prestation_annule\"]}[Data]",
                "in",
                "    Reporting_Prestation_annule"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a60faa9b-c25c-40e4-af40-a8c6cf54653f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a8091b71-da7e-41de-90a0-d2621808e6e3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d8a93aa3-d75b-47e1-8fc3-e59f9e969925",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "98acf41e-f88c-4556-b8a6-6b72ea722a59",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1b65da82-31fb-4ac3-a98f-6044c13d3aa8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "46c5657e-aff8-40e7-8e2d-bb641b0ab8be",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4f7caf4a-2140-4e43-a551-d6af7f079206",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b908af4f-3831-4796-8305-ca3c0c45e53d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3943f768-acd1-4412-aa21-7d4d67ab112c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3be0c2b1-867f-4935-a897-394fd4ea357f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3f0f3dae-2712-42f3-8d55-57306bb052a7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "05d5ed7e-d9ef-4f93-acff-a28a23baa2cf",
                "ordinal": 3
              }
            ],
            "lineageTag": "20e687a5-96ae-452b-88f7-0917bcff0a4e"
          }
        ],
        "isHidden": true,
        "lineageTag": "b481bb2b-ccaf-4b03-9e36-fb89a5d9a105",
        "partitions": [
          {
            "name": "LocalDateTable_a60faa9b-c25c-40e4-af40-a8c6cf54653f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Prestation_annule'[Date suppression])), 1, 1), Date(Year(MAX('Reporting Prestation_annule'[Date suppression])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_08212afe-ece0-4abe-8e80-9e00b104b9f5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "72501c2c-cfdb-4c50-9b0a-f1bc97e20b8d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f2088cd1-1439-4dca-9f4b-4d93099e64d2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b283fde2-1222-4596-8da4-1c0e775bcfd5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "cfb1078c-271e-4dce-9114-11459c5c1ebc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f81b6b33-34e2-40e9-ad40-25e3a4bad98e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a30cf138-02fe-4d86-ac89-3f7b3530c255",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7058df81-137d-4e61-9c23-9f68195c0797",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7c0e09ce-3c5a-45b2-9ca7-66138c3e62e1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "89562d57-25a1-4955-9917-cd4772bad4fd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b8159249-97f6-4c9a-93bc-6577a3761490",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "223dfd2a-6d49-4d78-8ba0-cee502af007e",
                "ordinal": 3
              }
            ],
            "lineageTag": "3cc70437-e4da-403e-9c14-1bbe12d7e0e0"
          }
        ],
        "isHidden": true,
        "lineageTag": "210c3c81-5b84-495a-b044-2ce9230b633a",
        "partitions": [
          {
            "name": "LocalDateTable_08212afe-ece0-4abe-8e80-9e00b104b9f5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Prestation_annule'[Date prestation])), 1, 1), Date(Year(MAX('Reporting Prestation_annule'[Date prestation])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9e05e250-3c67-4c7c-b0bb-041150b40c55",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8393477b-87ce-4c33-a4f9-77332a88b0ac",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f6668e26-5909-45b8-8ee0-39750646930e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f5a071c0-2c5a-4034-9e7d-3093b558f004",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "355452f3-8f54-4844-bb24-829b0bce01f4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "042e3ec2-0161-4be7-af23-8955f6852074",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "57907ca8-c9b5-4c65-bdcd-9231bd9033d6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "05bc38b3-7afd-4e63-a35c-55826e44a17d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d1116a8d-3c8e-4951-b120-2f20cad547a0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5ec00c51-375e-48fd-9cad-3f4cf10b5a75",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "755de4b1-3a73-4adc-8118-02696883836a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1d3254b4-6fa8-4a94-a012-1618b8fe789b",
                "ordinal": 3
              }
            ],
            "lineageTag": "6e90300d-463d-46a4-9255-f4e015421d4b"
          }
        ],
        "isHidden": true,
        "lineageTag": "2e15cf23-5fd7-465c-887d-493eb9ec49ad",
        "partitions": [
          {
            "name": "LocalDateTable_9e05e250-3c67-4c7c-b0bb-041150b40c55",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Prestation_annule'[Heure prestation])), 1, 1), Date(Year(MAX('Reporting Prestation_annule'[Heure prestation])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Reporting Suppression_avance",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dossier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c8e2833-fe4c-422c-b5a1-56acbad599e8",
            "sourceColumn": "Dossier",
            "summarizeBy": "none"
          },
          {
            "name": "Patient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88a7ae27-70ef-4683-af84-b8c157f69289",
            "sourceColumn": "Patient",
            "summarizeBy": "none"
          },
          {
            "name": "Date Avance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8cfb4358-ad0e-4d11-ba48-fe5d2aefb155",
            "sourceColumn": "Date Avance",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e65b8459-4980-4481-820c-ba77f6edd273"
                },
                "isDefault": true,
                "relationship": "4f59169f-6cb1-447f-88d6-5088ca6e5e93"
              }
            ]
          },
          {
            "name": "Heure Avance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b3e8d5f7-66b3-4941-a164-6320848e389f",
            "sourceColumn": "Heure Avance",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a11b5d35-863d-4f32-b536-99d7a77439cf"
                },
                "isDefault": true,
                "relationship": "85843a0e-3a10-4736-9266-a0fb47a0b763"
              }
            ]
          },
          {
            "name": "Utilisateur création",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4370982a-5ed2-4485-9647-719897320413",
            "sourceColumn": "Utilisateur création",
            "summarizeBy": "none"
          },
          {
            "name": "Montant avance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d8c45ede-22c7-43c3-add9-ba50509024a6",
            "sourceColumn": "Montant avance",
            "summarizeBy": "sum"
          },
          {
            "name": "Utilisateur suppression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1fd1f80-a6d7-4572-b233-6e9f7f844e5d",
            "sourceColumn": "Utilisateur suppression",
            "summarizeBy": "none"
          },
          {
            "name": "Date suppression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8349a75e-3067-49db-90fd-0aa3e794e2c9",
            "sourceColumn": "Date suppression",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b2cdc53a-8505-4a33-a7ba-ac24c0adf7ac"
                },
                "isDefault": true,
                "relationship": "cdfda844-6517-4826-aec7-2c94d0ef61b6"
              }
            ]
          }
        ],
        "lineageTag": "054729e4-368e-4827-935c-0d4dc32d196a",
        "measures": [
          {
            "name": "avance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum('Reporting Suppression_avance'[Montant avance]) )",
            "lineageTag": "6e975403-7d15-4937-98ad-9eb6d76fa20a"
          }
        ],
        "partitions": [
          {
            "name": "Reporting Suppression_avance",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    Reporting_Suppression_avance = Source{[Schema=\"Reporting\",Item=\"Suppression_avance\"]}[Data]",
                "in",
                "    Reporting_Suppression_avance"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e65b8459-4980-4481-820c-ba77f6edd273",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "01a0b563-00d1-4b11-8e2a-92d51c2ec7b5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cce98ab0-cff3-4c1e-b7be-4e135d6b5695",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9616ede6-df45-4e76-b1f0-80bd0f2a458c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "099d0a63-807b-4e8f-b5cc-a88681c0aa15",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7c3aec59-7c3d-4c6c-b38f-25901133ea5f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b1843d6d-9757-49e6-ad53-f94373290288",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "921a867b-a0e1-462e-9d00-60cbc4a7823a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "54c4572d-8a1a-4f91-8c9a-78e92de29e81",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "078d7d21-6c0d-4195-bed5-5f66e3f5f9c2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "200e47ba-4cb1-4467-97b1-ec1037403bf4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7decef3b-3502-4392-b006-117252968aaa",
                "ordinal": 3
              }
            ],
            "lineageTag": "27306186-ebd2-45e3-9f50-ba357b095966"
          }
        ],
        "isHidden": true,
        "lineageTag": "83749ed0-1e36-42e8-ae8e-5f58937c608b",
        "partitions": [
          {
            "name": "LocalDateTable_e65b8459-4980-4481-820c-ba77f6edd273",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Suppression_avance'[Date Avance])), 1, 1), Date(Year(MAX('Reporting Suppression_avance'[Date Avance])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a11b5d35-863d-4f32-b536-99d7a77439cf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "37917386-5fc2-4c5e-aec3-51d9a669ea5d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "40e9b78a-758f-4361-950b-647a5c02a504",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3bc05ee3-91d8-491a-b3b9-c56c1fe39826",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5763bac7-3b13-43ae-8491-cb56d11d7022",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9d208b1a-8273-4d46-a070-1ff290f2cdcc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cbb976e1-9b53-44e8-839c-ea5e456a3552",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c09ea913-c586-4ae7-9cde-e75edca78ebc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9efd30cb-972b-4ca3-ba9c-c90abfc88fc6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6cab78d4-1db8-481c-96a0-af356df1dc49",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e8fd08ed-e1dc-41a4-bb72-14f10c7f999e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "30376b23-2ead-4b62-bd4e-fd1147abfa11",
                "ordinal": 3
              }
            ],
            "lineageTag": "fe0267a1-8ccb-4cd0-a100-effc5fe9119b"
          }
        ],
        "isHidden": true,
        "lineageTag": "fbe1364a-a4ab-40a3-a0f8-7eb8e73e30d2",
        "partitions": [
          {
            "name": "LocalDateTable_a11b5d35-863d-4f32-b536-99d7a77439cf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Suppression_avance'[Heure Avance])), 1, 1), Date(Year(MAX('Reporting Suppression_avance'[Heure Avance])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b2cdc53a-8505-4a33-a7ba-ac24c0adf7ac",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e187f16b-d601-4b98-9e2f-06cc2f14d2de",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4ac8697f-b5ca-4362-928b-9c7f4b54c289",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "61bfc7e3-4b6a-4d52-b2e6-ee3ce6879fd9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ce439a51-19e0-47b7-8891-9efa219ff9e3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d8e130c4-990e-4b7c-8a93-19e95026ed9b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2fa93504-4fb7-472c-b57b-4d4c257c7bdd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4bb203ad-c8e1-401c-80a9-f179bb4086e8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2fd92238-c853-4d08-9d8b-8512deb0feb3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bedd8782-eeb3-4803-868c-e9ef5ee3e7eb",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0a47a12a-129a-4efd-913f-776d18be371c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "800cbfb8-4f42-4ae8-91ae-5757adcd7476",
                "ordinal": 3
              }
            ],
            "lineageTag": "55851eea-8cca-45da-a86a-94d523b4049c"
          }
        ],
        "isHidden": true,
        "lineageTag": "87bcecf0-1086-48c9-9373-9c3645b61c43",
        "partitions": [
          {
            "name": "LocalDateTable_b2cdc53a-8505-4a33-a7ba-ac24c0adf7ac",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Suppression_avance'[Date suppression])), 1, 1), Date(Year(MAX('Reporting Suppression_avance'[Date suppression])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Reporting Admission_annuler",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dossier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56301f81-c38e-4b2b-8eb1-2e25e8c3887e",
            "sourceColumn": "Dossier",
            "summarizeBy": "none"
          },
          {
            "name": "Utilisateur suppression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b786d61-82d1-4383-b5a2-b2bb79099fa9",
            "sourceColumn": "Utilisateur suppression",
            "summarizeBy": "none"
          },
          {
            "name": "Patient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6af63aea-e528-4fb9-af1c-21b4186faac1",
            "sourceColumn": "Patient",
            "summarizeBy": "none"
          },
          {
            "name": "Date arrivée",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "791cd0f7-611d-40d9-b850-675c7a7a9b0f",
            "sourceColumn": "Date arrivée",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9e203b7e-eb75-4bbe-9976-3e192f389d3a"
                },
                "isDefault": true,
                "relationship": "b213606c-2c04-406b-af5a-a013108cfeb9"
              }
            ]
          },
          {
            "name": "Date annulation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f4bdcff9-e79e-4fcf-a451-4920a5b79a8d",
            "sourceColumn": "Date annulation",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e2992f1c-fbda-4596-aaed-0ff256aac785"
                },
                "isDefault": true,
                "relationship": "9ee58c0d-44c0-4c51-b9de-f03822faa229"
              }
            ]
          }
        ],
        "lineageTag": "9375c288-ae1a-4129-8668-91e1541e0cea",
        "partitions": [
          {
            "name": "Reporting Admission_annuler",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    Reporting_Admission_annuler = Source{[Schema=\"Reporting\",Item=\"Admission_annuler\"]}[Data]",
                "in",
                "    Reporting_Admission_annuler"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9e203b7e-eb75-4bbe-9976-3e192f389d3a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "41cf34c9-f9d9-47d5-a258-7456ab59a185",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "37b6f907-8d13-4762-95eb-532e497a4e88",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9af1aab0-a7f1-4a66-a0d3-39673d449606",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "43dedd44-f782-467d-9de0-503e7179f59f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "28bf96f5-3b27-4fe2-af8a-a7756674072e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "657e8344-d0f2-41e3-a1f2-cd911d7fbe7a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6eac8e0c-92e0-4cfa-853f-25ddfcc6f1eb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "731864b2-8fc3-4fd9-8773-77c7124d996a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1857e0fe-ebb8-4d1f-8b11-4cd8ed99e039",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e381853e-628b-4617-a90e-913f8edb5cbd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a1889de1-3945-4063-8dd7-f7c92af4ce71",
                "ordinal": 3
              }
            ],
            "lineageTag": "abd57c26-5a21-42fb-be5b-697ecc6e6629"
          }
        ],
        "isHidden": true,
        "lineageTag": "a0c6ce89-f767-49c7-817a-21cd1ed357f7",
        "partitions": [
          {
            "name": "LocalDateTable_9e203b7e-eb75-4bbe-9976-3e192f389d3a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Admission_annuler'[Date arrivée])), 1, 1), Date(Year(MAX('Reporting Admission_annuler'[Date arrivée])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e2992f1c-fbda-4596-aaed-0ff256aac785",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "34e6a608-a117-4a38-bdb3-1d1743459c72",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d9998331-fc91-4998-b93b-5222af67152c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a61b0cee-cb53-4587-b94f-503a495c11af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6cb3af80-27ba-4f12-9de7-fa774fac323a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "783aae41-6d2c-49d9-a498-2931f934089d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5673ea83-2cdd-42c8-9bb7-a9266d3089bd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "395fe81e-c16d-4b7c-b492-821f32548514",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a3eb594e-b36c-47e6-b7a0-26fc530669bd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6a286e6d-ff7a-46db-9c54-c8264c68a18c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6d65753e-263e-4573-9a5f-71bbf0ad763a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9c661247-15df-4ff5-b484-9ea42429e181",
                "ordinal": 3
              }
            ],
            "lineageTag": "7f268277-d7ec-4b96-a7af-eec381c19920"
          }
        ],
        "isHidden": true,
        "lineageTag": "6cb90ef3-a4fe-41f0-ad1e-698507101c0c",
        "partitions": [
          {
            "name": "LocalDateTable_e2992f1c-fbda-4596-aaed-0ff256aac785",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Admission_annuler'[Date annulation])), 1, 1), Date(Year(MAX('Reporting Admission_annuler'[Date annulation])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Reporting Dossier_Payant_cloturer_Non_Paye",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dossier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16e604ae-99d4-41f6-ba71-87464e6953d3",
            "sourceColumn": "Dossier",
            "summarizeBy": "none"
          },
          {
            "name": "Patient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd60648c-b1f2-454c-9048-7a9ad8ddcb6a",
            "sourceColumn": "Patient",
            "summarizeBy": "none"
          },
          {
            "name": "Date arrivée",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a31b17f6-c52b-42ce-a09a-5b3597a8308d",
            "sourceColumn": "Date arrivée",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8aac830b-72ff-43c3-a415-5051460e140c"
                },
                "isDefault": true,
                "relationship": "a8f6619e-3d33-4f79-815c-b216715aaa2c"
              }
            ]
          }
        ],
        "lineageTag": "14f6496a-927e-4f6b-a155-5ca7ca192797",
        "partitions": [
          {
            "name": "Reporting Dossier_Payant_cloturer_Non_Paye",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    Reporting_Dossier_Payant_cloturer_Non_Paye = Source{[Schema=\"Reporting\",Item=\"Dossier_Payant_cloturer_Non_Paye\"]}[Data]",
                "in",
                "    Reporting_Dossier_Payant_cloturer_Non_Paye"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_8aac830b-72ff-43c3-a415-5051460e140c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d1e1c9e0-b6e0-4b6a-8803-8052574fa21b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ee04cd30-569b-46c6-8d31-94996473c331",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7968853e-d2c1-4a61-9970-421c677f91d5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "edc0beb5-9963-44fc-a971-94e5b057dd5e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "08c4c1b0-49aa-46ea-9ca4-cc9501756c27",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "889c848e-0d4a-4534-a75c-942d15cb13fb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4fd12545-3739-4589-bb70-12784fc7ff30",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "55b47deb-4f9e-4928-b1fa-9df55600ec30",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2e9f6d7a-24ad-464d-833d-5ce2eeac9c7e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a2567c2b-66d2-4a4c-8cd3-9de06f7aed15",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "73f78406-c795-4b73-9cad-59780d5425a9",
                "ordinal": 3
              }
            ],
            "lineageTag": "5a4baf6c-c3d9-4859-8181-0360368e3979"
          }
        ],
        "isHidden": true,
        "lineageTag": "a7290b83-d1cd-4909-9e5a-fb9687bb0f25",
        "partitions": [
          {
            "name": "LocalDateTable_8aac830b-72ff-43c3-a415-5051460e140c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Reporting Dossier_Payant_cloturer_Non_Paye'[Date arrivée])), 1, 1), Date(Year(MAX('Reporting Dossier_Payant_cloturer_Non_Paye'[Date arrivée])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VSTERILISATION",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "designation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6088b9de-7841-4ffe-9462-bae71a0008c0",
            "sourceColumn": "designation",
            "summarizeBy": "none"
          },
          {
            "name": "Nbr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8b389e2-6348-443e-96f1-1e15d56b12c9",
            "sourceColumn": "Nbr",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a69c5897-cc28-4e94-bd4b-b8606a9ae69d",
        "measures": [
          {
            "name": "nbr_actes",
            "expression": "CALCULATE(SUM(VSTERILISATION[Nbr]),FILTER(VSTERILISATION,VSTERILISATION[designation]=\"nbr_actes\"))",
            "formatString": "0",
            "lineageTag": "ad9132cc-17f2-40a5-a294-6869683229cc"
          },
          {
            "name": "nbr_boites_utilisés_annee_en_cours",
            "expression": "CALCULATE(SUM(VSTERILISATION[Nbr]),FILTER(VSTERILISATION,VSTERILISATION[designation]=\"nbr_boites_utilisés_annee_en_cours\"))",
            "formatString": "0",
            "lineageTag": "b4d7ab90-3253-4314-9b9a-5d2d85512a1a"
          },
          {
            "name": "nbr_instruments_abimés_annee_en_cours",
            "expression": "CALCULATE(SUM(VSTERILISATION[Nbr]),FILTER(VSTERILISATION,VSTERILISATION[designation]=\"nbr_instruments_abimés_annee_en_cours\"))",
            "formatString": "0",
            "lineageTag": "57d69ad5-1ae4-4e0c-b923-196490465f0c"
          },
          {
            "name": "nbr_instruments_perdus_annee_en_cours",
            "expression": "CALCULATE(SUM(VSTERILISATION[Nbr]),FILTER(VSTERILISATION,VSTERILISATION[designation]=\"nbr_instruments_perdus_annee_en_cours\"))",
            "formatString": "0",
            "lineageTag": "2ed38aa4-8535-4ca9-9b08-3a2263ec4ad2"
          },
          {
            "name": "nbr_instruments_utilisés_annee_en_cours",
            "expression": [
              "var a=CALCULATE(SUM(VSTERILISATION[Nbr]),FILTER(VSTERILISATION,VSTERILISATION[designation]=\"nbr_instruments_utilisés_annee_en_cours\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "12d90112-b07f-45c2-9044-d0627d47cbfc"
          },
          {
            "name": "Nombre de sorties boite",
            "expression": [
              "var a= CALCULATE(SUM(VSTERILISATION[Nbr]),FILTER(VSTERILISATION,VSTERILISATION[designation]=\"nbr_operations_annee_en_cours\"))",
              "RETURN IF(ISBLANK(a),0,a)"
            ],
            "formatString": "0",
            "lineageTag": "64c96e38-ae6f-4266-b91f-79a55bfe8222"
          }
        ],
        "partitions": [
          {
            "name": "VSTERILISATION",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_VSTERILISATION = Source{[Schema=\"dbo\",Item=\"VSTERILISATION\"]}[Data]",
                "in",
                "    dbo_VSTERILISATION"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "reporting effectif",
        "columns": [
          {
            "name": "year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8437203-ea67-4546-ada2-391290c80e23",
            "sourceColumn": "year",
            "summarizeBy": "sum"
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "897e1db4-bb29-4cf4-8c1c-f29e2d8f3b80",
            "sourceColumn": "month",
            "summarizeBy": "sum"
          },
          {
            "name": "MATEMP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a0c2832-efa7-4746-83f4-26fde37f6d01",
            "sourceColumn": "MATEMP",
            "summarizeBy": "none"
          },
          {
            "name": "libelleServ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b432d2bb-baca-4da7-820d-6d2376645a45",
            "sourceColumn": "libelleServ",
            "summarizeBy": "none"
          },
          {
            "name": "salaire_brut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0462245-b0fb-489b-8710-4a4453621d0c",
            "sourceColumn": "salaire_brut",
            "summarizeBy": "sum"
          },
          {
            "name": "masse_salariale",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "76baac86-8aa1-471c-8fef-df90c6112b4b",
            "sourceColumn": "masse_salariale",
            "summarizeBy": "sum"
          },
          {
            "name": "MATSER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ab948e9-ca42-412a-85b0-37416ebfeae7",
            "sourceColumn": "MATSER",
            "summarizeBy": "none"
          },
          {
            "name": "Clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70c22dbc-be6e-4729-80ec-63ea53404672",
            "sourceColumn": "Clinique",
            "summarizeBy": "none"
          },
          {
            "name": "mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "format(date('reporting effectif'[year],'reporting effectif'[month],01), \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "36de9e94-cb3e-4549-9201-19a136a5ba08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "moisannee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "format(date('reporting effectif'[year],'reporting effectif'[month],01), \"YYYYMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "241e3618-4619-44a4-9d8e-ead9702eef18",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "50b0bb87-d549-47c9-bc6e-e3347a4a51ec",
        "measures": [
          {
            "name": "eff_MOY",
            "expression": "sumx(DISTINCT('reporting effectif'[mois]), [effectif])/DISTINCTCOUNT('reporting effectif'[month])",
            "lineageTag": "3789d304-677a-457b-ac2f-17b3af6ea69c"
          },
          {
            "name": "effectif",
            "expression": "DISTINCTCOUNT('reporting effectif'[MATEMP])",
            "formatString": "0",
            "lineageTag": "14d9c31d-7bd0-44e1-ba1b-ed368f56064d"
          }
        ],
        "partitions": [
          {
            "name": "reporting effectif",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"154.144.241.43,1433\", \"Datawarehouse_Consolide\"),",
                "    reporting_effectif = Source{[Schema=\"reporting\",Item=\"effectif\"]}[Data]",
                "in",
                "    reporting_effectif"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "reporting cotisation",
        "columns": [
          {
            "name": "matser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06b1c901-5df3-4769-a86c-500af094a3f7",
            "sourceColumn": "matser",
            "summarizeBy": "none"
          },
          {
            "name": "CodRubrique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56e96954-15ba-4f85-a7a7-0c3b99072dfd",
            "sourceColumn": "CodRubrique",
            "summarizeBy": "none"
          },
          {
            "name": "LibRubrique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc0b78fe-15e8-452e-a7b5-d5b69a71b9e4",
            "sourceColumn": "LibRubrique",
            "summarizeBy": "none"
          },
          {
            "name": "Dat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "677f05a9-acc8-49e1-9247-6fd0a6846f2b",
            "sourceColumn": "Dat",
            "summarizeBy": "none"
          },
          {
            "name": "MntEmployeur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "09ddff71-7475-4607-8f48-ea532830f3f1",
            "sourceColumn": "MntEmployeur",
            "summarizeBy": "sum"
          },
          {
            "name": "matemp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c891824-1759-4e08-907a-f22668651c93",
            "sourceColumn": "matemp",
            "summarizeBy": "none"
          },
          {
            "name": "Clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3213bb2e-3edf-4194-8727-d63353e574db",
            "sourceColumn": "Clinique",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "73446d79-3f1d-4ea4-a380-eeb3e7c37b31",
        "measures": [
          {
            "name": "MntEmp",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum('reporting cotisation'[MntEmployeur])",
            "lineageTag": "714c9af0-d3a4-4d5e-9022-436a958649f1"
          }
        ],
        "partitions": [
          {
            "name": "reporting cotisation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"154.144.241.43,1433\", \"Datawarehouse_Consolide\"),",
                "    reporting_cotisation = Source{[Schema=\"reporting\",Item=\"cotisation\"]}[Data]",
                "in",
                "    reporting_cotisation"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "reporting salaire",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86637ff6-00e8-4c2b-80cd-b748ad8d7a8b",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "matser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ae33251-e6a5-43e5-8661-fd2fea072279",
            "sourceColumn": "matser",
            "summarizeBy": "none"
          },
          {
            "name": "service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe081f07-4393-447d-b53b-0739fea761c2",
            "sourceColumn": "service",
            "summarizeBy": "none"
          },
          {
            "name": "MATEMP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2dec77b-f387-4ac1-8c5b-13adbd7e6475",
            "sourceColumn": "MATEMP",
            "summarizeBy": "none"
          },
          {
            "name": "SalBase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "470021de-6fa4-4933-bea1-e463746c6280",
            "sourceColumn": "SalBase",
            "summarizeBy": "sum"
          },
          {
            "name": "SalBrut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15a76f32-69f0-48a3-8af1-3007d0e9558b",
            "sourceColumn": "SalBrut",
            "summarizeBy": "sum"
          },
          {
            "name": "MntChPat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6803a287-c746-4ca8-8c0d-30a5e2429ae6",
            "sourceColumn": "MntChPat",
            "summarizeBy": "sum"
          },
          {
            "name": "MntTFP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8df83c3e-2fc4-4217-99ea-8c05ece8b3be",
            "sourceColumn": "MntTFP",
            "summarizeBy": "sum"
          },
          {
            "name": "MntFOPROLOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9a11e61-c638-4d58-aa09-3f4253262c11",
            "sourceColumn": "MntFOPROLOS",
            "summarizeBy": "sum"
          },
          {
            "name": "MntAcc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2bc8da3d-5840-4cbe-9492-c2733c57319b",
            "sourceColumn": "MntAcc",
            "summarizeBy": "sum"
          },
          {
            "name": "MntComplementRetraite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3db2455-7f4f-45b2-807b-b1c87f48ec12",
            "sourceColumn": "MntComplementRetraite",
            "summarizeBy": "sum"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8a600f5b-71af-47dd-93f7-d4e7efdb1361",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "MtConge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d51fc7e-020a-4521-8837-607e01cc8c3f",
            "sourceColumn": "MtConge",
            "summarizeBy": "sum"
          },
          {
            "name": "soldecongepaye",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f93d2161-9393-4fdc-a441-c3492c66c4e5",
            "sourceColumn": "soldecongepaye",
            "summarizeBy": "sum"
          },
          {
            "name": "MntAss_employeur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "73e557c2-fbba-4d4d-acbc-fcd2da6f3092",
            "sourceColumn": "MntAss_employeur",
            "summarizeBy": "sum"
          },
          {
            "name": "Clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0e979ca-cfd2-474f-ab8b-ae3658a76018",
            "sourceColumn": "Clinique",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "091a9515-c133-4d42-8e49-f91305707bdf",
        "measures": [
          {
            "name": "Salaire de base et compléments",
            "expression": "[Salaire de base] + [prime]+ sum('reporting salaire'[soldecongepaye])+sum('reporting salaire'[MtConge])",
            "lineageTag": "9a373b18-f76d-43cf-b6ab-a68c8550b862"
          },
          {
            "name": "Salaire de base",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum('reporting salaire'[SalBase])",
            "lineageTag": "af0f0894-2529-4c50-9fc3-b23219aebf15"
          },
          {
            "name": "salaire brut",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum('reporting salaire'[SalBrut])",
            "lineageTag": "938c11e1-4beb-42e0-be66-44adc3e2fc21"
          },
          {
            "name": "MS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum('reporting salaire'[SalBrut])+sum('reporting cotisation'[MntEmployeur]) --sum('reporting salaire'[MntAcc])+sum('reporting salaire'[MntChPat])+sum('reporting salaire'[MntTFP])+sum('reporting salaire'[MntAss_employeur])+sum('reporting salaire'[MntFOPROLOS])+sum('reporting salaire'[SalBrut])",
            "lineageTag": "dae6196d-d7b2-4f40-8b79-aeab2fe953dc"
          },
          {
            "name": "ratio_CA%",
            "expression": "DIVIDE([MS],[montant_CA],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "71c8be5d-093d-4fd3-9d1b-7e4df4f152df"
          },
          {
            "name": "MSY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "TOTALMTD([MS],Dates[Date])",
            "lineageTag": "94a00895-d6c6-4c4d-80c9-c73ed407ac07"
          },
          {
            "name": "MSY-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "TOTALMTD([MS],DATEADD(Dates[Date],-1,year))",
            "lineageTag": "28d51f3b-a4a7-40cf-8eda-c1969d41f21e"
          },
          {
            "name": "RatioMTD",
            "expression": "totalmtd([ratio_CA%],Dates[Date])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "695b4ce0-d770-44c2-af7e-a08e232e57a8"
          },
          {
            "name": "RatioMTDY-1",
            "expression": "TOTALMTD([ratio_CA%],DATEADD(Dates[Date],-1,year))",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "045c5faf-657d-42e2-85c7-7959eee8d273"
          },
          {
            "name": "Contrubition des personnels",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[montant_CA]/[eff_MOY]",
            "lineageTag": "1a565a6f-26ef-461d-b366-5e67c1a53633"
          }
        ],
        "partitions": [
          {
            "name": "reporting salaire",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"154.144.241.43,1433\", \"Datawarehouse_Consolide\"),",
                "    reporting_salaire = Source{[Schema=\"reporting\",Item=\"salaire\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(reporting_salaire, each ([Clinique] = \"MAR\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "reporting heure_supp",
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8ffefb7-523f-42f7-b924-6d4ee1d27cc5",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "matser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e026105-4863-4663-9905-d996c1603d29",
            "sourceColumn": "matser",
            "summarizeBy": "none"
          },
          {
            "name": "service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9e2ad54-b940-45bb-a940-98137b6cdcba",
            "sourceColumn": "service",
            "summarizeBy": "none"
          },
          {
            "name": "Matemp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d10f9c9a-fe0f-427e-b3be-26832a55e255",
            "sourceColumn": "Matemp",
            "summarizeBy": "none"
          },
          {
            "name": "CODMAJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f33f817-41ee-4367-9a25-48f9eaaaa03f",
            "sourceColumn": "CODMAJ",
            "summarizeBy": "none"
          },
          {
            "name": "numsession",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16bef6f3-a6cb-442b-b868-23dbfe92f842",
            "sourceColumn": "numsession",
            "summarizeBy": "sum"
          },
          {
            "name": "dat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "099e547e-12cb-4f38-a2a8-4f4a4f4867f1",
            "sourceColumn": "dat",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_137e3c2f-f97a-4860-8e0d-8a8bad887304"
                },
                "isDefault": true,
                "relationship": "0bbd8ef4-412d-47f4-ac7b-e86ec678cafa"
              }
            ]
          },
          {
            "name": "montant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc6f7fc3-b804-40b7-8485-9151fd540567",
            "sourceColumn": "montant",
            "summarizeBy": "sum"
          },
          {
            "name": "libmaj",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f986c86e-4d6c-448e-8983-ab2c00c3da4b",
            "sourceColumn": "libmaj",
            "summarizeBy": "none"
          },
          {
            "name": "Clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e04e9651-d20f-4512-99e3-9212bcfd9e91",
            "sourceColumn": "Clinique",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1edbf55e-122e-4e4c-889d-e22b75937a63",
        "measures": [
          {
            "name": "vacation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum('reporting heure_supp'[montant])",
            "lineageTag": "ecdf4a25-2622-40db-9579-b468ef415a92"
          }
        ],
        "partitions": [
          {
            "name": "reporting heure_supp",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"154.144.241.43,1433\", \"Datawarehouse_Consolide\"),",
                "    reporting_heure_supp = Source{[Schema=\"reporting\",Item=\"heure_supp\"]}[Data]",
                "in",
                "    reporting_heure_supp"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_137e3c2f-f97a-4860-8e0d-8a8bad887304",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bc7e8436-a055-4bdf-8e16-79facd10635a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5f56a655-1e45-40ec-be31-6ffaba0c14fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "59f11972-327a-4b29-a616-a7765c5d8ed4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3bfe4e35-4a36-489e-843d-f48f75b94567",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f5d94d4d-0ead-47c2-8677-f8fdb026b99e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8d633ba2-5c12-4e08-81da-3bbed16e17a6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "186f7984-a5ed-4b55-b944-2374c5d2bbbc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "640e9d5d-92d5-421e-b67c-09ddf739e5a2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "74036f4f-6ca9-4624-8ed3-f6b88f9cbff1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "43c6a3e6-f1a8-42b1-8565-57dc9a247a46",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "adf1792a-976b-40e0-b499-abd0002520f4",
                "ordinal": 3
              }
            ],
            "lineageTag": "c894880a-2f83-4872-8984-e31db172f0f1"
          }
        ],
        "isHidden": true,
        "lineageTag": "8926697a-9bd9-4aba-a759-e08852532e9f",
        "partitions": [
          {
            "name": "LocalDateTable_137e3c2f-f97a-4860-8e0d-8a8bad887304",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('reporting heure_supp'[dat])), 1, 1), Date(Year(MAX('reporting heure_supp'[dat])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "reporting prime",
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04aeb252-7a52-4edc-aa5c-35e07631f5b6",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "CODPRIM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "468a4a71-71f8-47e4-85f8-399534b20806",
            "sourceColumn": "CODPRIM",
            "summarizeBy": "none"
          },
          {
            "name": "LibPrim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d31b0081-252a-46b3-8a85-8d7ff94e1bef",
            "sourceColumn": "LibPrim",
            "summarizeBy": "none"
          },
          {
            "name": "MatSer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7feb6bf-3a92-472f-8df6-ef3c1c86fb5f",
            "sourceColumn": "MatSer",
            "summarizeBy": "none"
          },
          {
            "name": "service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54f444f6-3094-4fe5-a0f2-a053f2618588",
            "sourceColumn": "service",
            "summarizeBy": "none"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "28bf7ff0-f1e1-4db3-a640-fd3abe7b8343",
            "sourceColumn": "date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_22e0cf24-75e7-40be-9ccf-5d86ebdca70a"
                },
                "isDefault": true,
                "relationship": "97b47a86-5498-4806-841b-8b24dfd8fee4"
              }
            ]
          },
          {
            "name": "MtPrim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56a5595d-1af0-401d-9b8b-3d45b3bf811b",
            "sourceColumn": "MtPrim",
            "summarizeBy": "sum"
          },
          {
            "name": "MATEMP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3f05ceb-3035-4e3e-90f8-3dbf2930e0c4",
            "sourceColumn": "MATEMP",
            "summarizeBy": "none"
          },
          {
            "name": "numsession",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "af926e53-672d-449f-b69c-69875dd7f5e5",
            "sourceColumn": "numsession",
            "summarizeBy": "sum"
          },
          {
            "name": "Clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03adf1f2-1f3d-44fb-83d8-7fddf283ada4",
            "sourceColumn": "Clinique",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a5273ada-412c-42a3-ad17-b258c478c9cf",
        "measures": [
          {
            "name": "prime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "sum('reporting prime'[MtPrim])",
            "lineageTag": "99e3a247-3e96-4234-8f4d-52116cc894e1"
          }
        ],
        "partitions": [
          {
            "name": "reporting prime",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"154.144.241.43,1433\", \"Datawarehouse_Consolide\"),",
                "    reporting_prime = Source{[Schema=\"reporting\",Item=\"prime\"]}[Data]",
                "in",
                "    reporting_prime"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_22e0cf24-75e7-40be-9ccf-5d86ebdca70a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6b17568e-792a-4caa-ac25-172d8e21daf1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c71150a3-d020-49e2-b36a-b6f9e0d9cbaa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "992928c7-e774-4f93-bc72-67717201770d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d9b9d0ee-b57a-4988-9b8d-756449644fda",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "58b04790-627a-42a5-bdf8-827d49fa8d12",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "42dad03c-dfbd-4ab5-8dc8-f715efe3a34f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8fcfb136-0cf5-4b60-938c-a4145fc5e0cc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "54422ba5-10d0-4ead-90ff-83dffd5ac5fc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "138937fa-c10e-40e0-a8d7-aedf89702576",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "82e4427a-d604-4c92-ae6e-0bc2a1c074e3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d5286d03-b6dd-48a1-8beb-e4ba5df00ca7",
                "ordinal": 3
              }
            ],
            "lineageTag": "370bd188-e674-4aa0-9147-7557628770cf"
          }
        ],
        "isHidden": true,
        "lineageTag": "903c3625-c421-4cbb-8243-6eb1ad7a6bdd",
        "partitions": [
          {
            "name": "LocalDateTable_22e0cf24-75e7-40be-9ccf-5d86ebdca70a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('reporting prime'[date])), 1, 1), Date(Year(MAX('reporting prime'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Dates",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "85e1a97792e6462293b46050db44ef5e"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b366010e-ae7a-44d0-ba0c-c325c8ac192b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9a7f01e8-a7fa-4689-91b2-feb5608b4ba7"
                },
                "isDefault": true,
                "relationship": "6318917f-5357-45ca-bf3f-b83946fd7282"
              }
            ]
          },
          {
            "name": "mois annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(Dates[Date],\"YYYYMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "f248180c-06d3-4048-8fe7-c01a8d01d6de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "year_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "year(Dates[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7661e80a-a3f6-47a1-98de-7fa480bc623f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(Dates[Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "1639f99f-1d49-4a73-9cc4-9815da04a62b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c09034ce-e6f4-47ae-8b8f-f7806be18045",
        "measures": [
          {
            "name": "MaxXYear",
            "expression": "year(TODAY())",
            "formatString": "0",
            "lineageTag": "e4f0a74d-8fd9-48ba-a828-90ef1f4c48c4"
          }
        ],
        "partitions": [
          {
            "name": "Dates",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(\"01/01/2010\",TODAY())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ClFacture",
        "columns": [
          {
            "name": "NumDoss",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb758b6c-f4aa-408c-8f83-8fdb2282f204",
            "sourceColumn": "NumDoss",
            "summarizeBy": "none"
          },
          {
            "name": "NumCha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d639d40-7547-45f5-9d33-5f48bf7ca99b",
            "sourceColumn": "NumCha",
            "summarizeBy": "none"
          },
          {
            "name": "NumSer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8183c6e3-9ce8-42ca-8644-b6d818822ebb",
            "sourceColumn": "NumSer",
            "summarizeBy": "none"
          },
          {
            "name": "NatSer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33abe663-c8e6-45f2-8575-84804e0f5905",
            "sourceColumn": "NatSer",
            "summarizeBy": "none"
          },
          {
            "name": "NumBon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c311d09e-4fa2-4429-99cb-0b27fed9ed73",
            "sourceColumn": "NumBon",
            "summarizeBy": "none"
          },
          {
            "name": "Montant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aa0dcac3-cb61-4286-a234-0547f3354aa0",
            "sourceColumn": "Montant",
            "summarizeBy": "sum"
          },
          {
            "name": "Remise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a5f033a9-2062-4eb3-ac57-4c64365ee9d7",
            "sourceColumn": "Remise",
            "summarizeBy": "sum"
          },
          {
            "name": "CodeTva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53d16b64-7627-4cea-ad7e-88f4f498f108",
            "sourceColumn": "CodeTva",
            "summarizeBy": "none"
          },
          {
            "name": "TauxTva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79a6e10e-49e6-4799-ab0c-dd675e5e6319",
            "sourceColumn": "TauxTva",
            "summarizeBy": "sum"
          },
          {
            "name": "DatOpe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "429ad3e6-f699-4b6c-9a68-1d55d2c79d2b",
            "sourceColumn": "DatOpe",
            "summarizeBy": "none"
          },
          {
            "name": "HeuOpe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "af394c37-f53f-4f99-ad4b-ae6bff4feba3",
            "sourceColumn": "HeuOpe",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6dbfa5a2-7d5e-4d69-b347-8b79a80803d3"
                },
                "isDefault": true,
                "relationship": "561e007e-ea1c-4b64-adc3-e3e0092e4b21"
              }
            ]
          },
          {
            "name": "NumFac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "825074d9-37fa-47a6-b66e-8be22732dabb",
            "sourceColumn": "NumFac",
            "summarizeBy": "none"
          },
          {
            "name": "DatFac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d072ca55-392c-485f-8174-990756b2d51c",
            "sourceColumn": "DatFac",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c5b42fc4-4d63-4130-85dc-64b9426da457"
                },
                "isDefault": true,
                "relationship": "5b256c9a-070b-4971-bab3-1ab5dde0bd8d"
              }
            ]
          },
          {
            "name": "Etat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cde9b93-add0-4415-ac2b-abbee17c6e21",
            "sourceColumn": "Etat",
            "summarizeBy": "none"
          },
          {
            "name": "Cloturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "39b4454f-9726-4f56-84b0-d1fd9419d9cb",
            "sourceColumn": "Cloturer",
            "summarizeBy": "none"
          },
          {
            "name": "UserCre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e8bb365-3d2f-4e87-9dc8-dcb86557ee60",
            "sourceColumn": "UserCre",
            "summarizeBy": "none"
          },
          {
            "name": "PEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7eeec579-cad1-4cc7-b8fc-b38a7dc7f87b",
            "sourceColumn": "PEC",
            "summarizeBy": "sum"
          },
          {
            "name": "PECTva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "43d2db0d-8c68-4041-b985-17feb9d28c3d",
            "sourceColumn": "PECTva",
            "summarizeBy": "sum"
          },
          {
            "name": "NumVir",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9e4e3c2-87fb-4094-aa2c-7c3b5d75577f",
            "sourceColumn": "NumVir",
            "summarizeBy": "none"
          },
          {
            "name": "OldTVA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dfcb69d-d5c7-44f8-9ffd-4574a25f25c0",
            "sourceColumn": "OldTVA",
            "summarizeBy": "none"
          },
          {
            "name": "OldTauTVA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "534b8f8e-e321-403a-b668-18cc49eb6d7a",
            "sourceColumn": "OldTauTVA",
            "summarizeBy": "sum"
          },
          {
            "name": "TypExon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbd9ad5a-62a9-4640-8af5-3c37f903606f",
            "sourceColumn": "TypExon",
            "summarizeBy": "none"
          },
          {
            "name": "PriUni",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d9ca592-393a-4764-9e9a-6eb453bdab6f",
            "sourceColumn": "PriUni",
            "summarizeBy": "sum"
          },
          {
            "name": "Qte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6a3631aa-71d7-4ad4-a9f0-fdde91afb13b",
            "sourceColumn": "Qte",
            "summarizeBy": "sum"
          },
          {
            "name": "TypMed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeb76eb6-4d12-400a-8025-a6eaa67a48cb",
            "sourceColumn": "TypMed",
            "summarizeBy": "none"
          },
          {
            "name": "Convention",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "27c16687-a8af-41bc-ae8f-88c458c2c4a3",
            "sourceColumn": "Convention",
            "summarizeBy": "none"
          },
          {
            "name": "OldPriUni",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bf7beae5-812e-4afd-92d4-5c2fd4f4dd00",
            "sourceColumn": "OldPriUni",
            "summarizeBy": "sum"
          },
          {
            "name": "OldMontant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4416440c-1071-4b7d-88c6-bad48da0319f",
            "sourceColumn": "OldMontant",
            "summarizeBy": "sum"
          },
          {
            "name": "NumDossPatient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ce9c692-d9d2-4c93-bbdf-f40be9d3f516",
            "sourceColumn": "NumDossPatient",
            "summarizeBy": "none"
          },
          {
            "name": "Codsup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "169337ec-8520-4b99-9c62-a718193c41a1",
            "sourceColumn": "Codsup",
            "summarizeBy": "none"
          },
          {
            "name": "UserDel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3633b765-fea9-42ae-92ff-c35eaca66481",
            "sourceColumn": "UserDel",
            "summarizeBy": "none"
          },
          {
            "name": "Datdel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "15e9cc99-c440-4492-bc8e-ead2e9058255",
            "sourceColumn": "Datdel",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dc08e2f9-2e5d-4293-aebb-3f213209a326"
                },
                "isDefault": true,
                "relationship": "fd28d40c-e0a9-45fc-be0b-13b6fc892bfc"
              }
            ]
          },
          {
            "name": "Dec_Med",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3392abcd-0148-4b82-a58c-9d88ace6aaa0",
            "sourceColumn": "Dec_Med",
            "summarizeBy": "none"
          },
          {
            "name": "Compteur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c92db723-46cd-4c4a-a205-c1d36f0735fe",
            "sourceColumn": "Compteur",
            "summarizeBy": "sum"
          },
          {
            "name": "PrestInclus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98ceb924-8bb6-4476-9a91-cb5543e3bcad",
            "sourceColumn": "PrestInclus",
            "summarizeBy": "none"
          },
          {
            "name": "PECCNAM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ae19e60-a1cb-4f1e-9607-d94f7dcfb767",
            "sourceColumn": "PECCNAM",
            "summarizeBy": "sum"
          },
          {
            "name": "ConvPayant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e221b571-e728-4bfd-84d9-67b62b3011a6",
            "sourceColumn": "ConvPayant",
            "summarizeBy": "none"
          },
          {
            "name": "MajorPayant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2ede746d-933b-457b-b92a-156662bcecb3",
            "sourceColumn": "MajorPayant",
            "summarizeBy": "sum"
          },
          {
            "name": "MajorPers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa89af09-105e-46ba-8889-0ee350ae46a8",
            "sourceColumn": "MajorPers",
            "summarizeBy": "sum"
          },
          {
            "name": "ConvPers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f8f9521f-c8b6-4b1d-934f-bf81a4cd6bd8",
            "sourceColumn": "ConvPers",
            "summarizeBy": "none"
          },
          {
            "name": "Tx_Majoration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4be98d9b-66f2-4c27-a287-9062f91b81c6",
            "sourceColumn": "Tx_Majoration",
            "summarizeBy": "sum"
          },
          {
            "name": "User_Remise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96fc7fda-ae5a-4629-b737-8345f09890a5",
            "sourceColumn": "User_Remise",
            "summarizeBy": "none"
          },
          {
            "name": "Date_Remise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6fa51652-08dc-405b-958a-f7d75a33fa17",
            "sourceColumn": "Date_Remise",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e2f21bfc-d774-4e2b-84d2-cd41e8fad56f"
                },
                "isDefault": true,
                "relationship": "5ec29747-c6e7-46e5-8f31-fa2d24f1289b"
              }
            ]
          },
          {
            "name": "codtypForfait",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d711a28-bf5f-4221-b372-5f651410f5e3",
            "sourceColumn": "codtypForfait",
            "summarizeBy": "none"
          },
          {
            "name": "CodResponsableRemise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6568f10d-16f3-4af9-a325-8e8080be343f",
            "sourceColumn": "CodResponsableRemise",
            "summarizeBy": "none"
          },
          {
            "name": "Numero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f322d9e-586e-4597-a0aa-cab7a605606f",
            "sourceColumn": "Numero",
            "summarizeBy": "sum"
          },
          {
            "name": "Mt_Avance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "20e814e5-f3fb-49bb-aaf0-23a52788aef0",
            "sourceColumn": "Mt_Avance",
            "summarizeBy": "sum"
          },
          {
            "name": "CodeTvaMed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd8245ee-9903-4f6d-b5c0-a9a737b7ee42",
            "sourceColumn": "CodeTvaMed",
            "summarizeBy": "none"
          },
          {
            "name": "TauxTvaMed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2454b01-d0e9-447f-88cb-ef0bf73afe33",
            "sourceColumn": "TauxTvaMed",
            "summarizeBy": "sum"
          },
          {
            "name": "MontantHTMed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "136cbcc4-d0f7-4e54-b6ea-e75b40ec1ee0",
            "sourceColumn": "MontantHTMed",
            "summarizeBy": "sum"
          },
          {
            "name": "MontantTVAMed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0d5a5ca0-3378-44b8-b13f-c2e172be8893",
            "sourceColumn": "MontantTVAMed",
            "summarizeBy": "sum"
          },
          {
            "name": "NatureActe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa9f1dd8-9eba-43ff-ad4b-896f0791fe62",
            "sourceColumn": "NatureActe",
            "summarizeBy": "none"
          },
          {
            "name": "lettrageDevis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4f099abb-7b3b-429f-9b83-7238c4a3d7ab",
            "sourceColumn": "lettrageDevis",
            "summarizeBy": "none"
          },
          {
            "name": "numlettrage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05de105c-aedc-4c73-81cf-bd2a40094932",
            "sourceColumn": "numlettrage",
            "summarizeBy": "none"
          },
          {
            "name": "NumDemande",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c8f8d33-6fe1-4ff7-b343-6392068df05d",
            "sourceColumn": "NumDemande",
            "summarizeBy": "none"
          },
          {
            "name": "numDevis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ff4c50c-0737-4a77-9b83-5eb851c2f9e1",
            "sourceColumn": "numDevis",
            "summarizeBy": "none"
          },
          {
            "name": "Etat_Imp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ed70d68-3888-4344-bb0e-4538b5849381",
            "sourceColumn": "Etat_Imp",
            "summarizeBy": "none"
          },
          {
            "name": "numbord",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55173232-6668-422d-b665-c5200d1e5ae6",
            "sourceColumn": "numbord",
            "summarizeBy": "none"
          },
          {
            "name": "compteur_origine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "686d79c3-73ff-4033-8cdf-edb42147722c",
            "sourceColumn": "compteur_origine",
            "summarizeBy": "sum"
          },
          {
            "name": "numbon_dupp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3134b5f-4f2a-43a7-b07e-a0ba5c9016c6",
            "sourceColumn": "numbon_dupp",
            "summarizeBy": "none"
          },
          {
            "name": "patente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "912566bf-a1b4-486f-994a-4953e51577bf",
            "sourceColumn": "patente",
            "summarizeBy": "none"
          },
          {
            "name": "Assurence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bace5268-e383-45fb-917d-873a04ce42b7",
            "sourceColumn": "Assurence",
            "summarizeBy": "none"
          },
          {
            "name": "CodMedPay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "032327bf-7d2b-42e7-b385-d2cebf3e186d",
            "sourceColumn": "CodMedPay",
            "summarizeBy": "none"
          },
          {
            "name": "compteur_origine_scinder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6bae3a0-0ad9-4887-84b7-cec8ff9d2c53",
            "sourceColumn": "compteur_origine_scinder",
            "summarizeBy": "sum"
          },
          {
            "name": "NumConv",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e25c461-e3d1-40f6-85b2-1c62a41f86da",
            "sourceColumn": "NumConv",
            "summarizeBy": "none"
          },
          {
            "name": "Tx_Majoration_dupp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63cac87f-d59e-4c7d-b4ac-575d344f1034",
            "sourceColumn": "Tx_Majoration_dupp",
            "summarizeBy": "sum"
          },
          {
            "name": "LettreCle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9645d49-8c36-4463-b0b8-add63ec8cba8",
            "sourceColumn": "LettreCle",
            "summarizeBy": "none"
          },
          {
            "name": "des_impression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d13342c7-83ce-4423-b4c9-69e22ce0b2fa",
            "sourceColumn": "des_impression",
            "summarizeBy": "none"
          },
          {
            "name": "nature_impression",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec7ff4bb-0f49-41d0-8680-47d26a828434",
            "sourceColumn": "nature_impression",
            "summarizeBy": "none"
          },
          {
            "name": "Abandon_HO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2538c62-3a34-4d48-95aa-1927c32ac870",
            "sourceColumn": "Abandon_HO",
            "summarizeBy": "none"
          },
          {
            "name": "valider_ho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1b979261-84d4-4718-947a-9eebe684727b",
            "sourceColumn": "valider_ho",
            "summarizeBy": "none"
          },
          {
            "name": "user_valider_ho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e66c30c1-bd6f-454d-8ce6-7c510a4dd568",
            "sourceColumn": "user_valider_ho",
            "summarizeBy": "none"
          },
          {
            "name": "date_valider_ho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e4ac2edf-1aa2-430a-b1ad-fa5b76e6baec",
            "sourceColumn": "date_valider_ho",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e39e7027-7cab-4869-99f4-0ec0692a857b"
                },
                "isDefault": true,
                "relationship": "b8fb393b-98af-4654-9120-0c78f81074eb"
              }
            ]
          }
        ],
        "lineageTag": "2a2d82f9-f59a-463a-8bab-3c143efc63ba",
        "measures": [
          {
            "name": "montant_ca",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(ClFacture, ClFacture[Montant] * (1 - ClFacture[Remise])),",
              "    FILTER(ClFacture, ClFacture[NatSer] = \"c\")",
              ")",
              ""
            ],
            "lineageTag": "0b28b6c5-9c1b-4d86-a34a-fa6a864b4040"
          }
        ],
        "partitions": [
          {
            "name": "ClFacture",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"192.168.1.109\\SQL2019\", \"tb_datawarehouse\"),",
                "    dbo_ClFacture = Source{[Schema=\"dbo\",Item=\"ClFacture\"]}[Data]",
                "in",
                "    dbo_ClFacture"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6dbfa5a2-7d5e-4d69-b347-8b79a80803d3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0ff00254-4595-446f-bfbe-b26f35352c48",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "a97e94cd-a30a-4f91-9f74-cd9a64606c72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5d87f502-3b22-4cfc-961d-55ec150063c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4ea65f69-5c7d-4ab4-896d-d327e18221e4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9483a0d4-5dc8-474a-9be8-3a07064b2ed6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a5fd90a5-a626-40e3-9a82-7a0fc201cf9f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5a9f0099-8ecd-4373-b8e6-4ca5b6b7f95b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "de744401-3b39-4113-ad2c-a2480690957c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e82e15d1-358a-4da5-b9b4-b43b1cbf448b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3f73716c-0eeb-4d8e-8296-f486eeb6c797",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "104e3c8e-7b31-46db-8be3-2acfeb4074a5",
                "ordinal": 3
              }
            ],
            "lineageTag": "5a4a21bd-fff1-499b-bbc1-5b1e4a9df61f"
          }
        ],
        "isHidden": true,
        "lineageTag": "09311b37-4916-489e-b48e-c1add2f39605",
        "partitions": [
          {
            "name": "LocalDateTable_6dbfa5a2-7d5e-4d69-b347-8b79a80803d3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ClFacture'[HeuOpe])), 1, 1), Date(Year(MAX('ClFacture'[HeuOpe])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c5b42fc4-4d63-4130-85dc-64b9426da457",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1233a4b9-36eb-42a2-8347-ead5fcc2dfbd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "370dbb13-df87-420d-b475-ae7e6cc7c7bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "acbe12fc-8049-4dd7-b08e-887c7d972622",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "80ccc27e-7597-42ce-b032-8ae7cb5e1467",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "170f6ca7-e22a-4b76-841d-44c344a2f229",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3b97ae55-16cc-4036-873d-f474cb63a13d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "80bbe4e9-bffa-48d7-ba62-9eed7ecf6f9e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "05cb835f-ee48-4ea7-b02a-54054524fc7f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5d88daa0-c7bf-43fc-8a8b-a31817624a5b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "42815e97-fd28-410c-a487-99d62e4a25bf",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ea2d6953-3a01-47d5-a88e-e569d69c5304",
                "ordinal": 3
              }
            ],
            "lineageTag": "f4e1b221-3f32-4e0c-a55e-bfb61636690f"
          }
        ],
        "isHidden": true,
        "lineageTag": "08abd443-7411-4607-818f-a7ed6dd0c183",
        "partitions": [
          {
            "name": "LocalDateTable_c5b42fc4-4d63-4130-85dc-64b9426da457",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ClFacture'[DatFac])), 1, 1), Date(Year(MAX('ClFacture'[DatFac])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_dc08e2f9-2e5d-4293-aebb-3f213209a326",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c90c237b-a811-4ce0-a3b9-9b238d0d9543",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "65bea59a-3a90-4ce5-8840-6c23e6d6a960",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6e15e9c3-ade1-4940-ab14-eac3c609fb3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "785ba88a-561f-4d90-929e-b2500e05a110",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3783862e-2c0c-4aaa-aaed-6fff64dd90ac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "93c0e2ec-39a1-4deb-b147-9cead0838b09",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "51794436-a0d6-41a1-82a7-c5c57ba64aa5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7b271051-7023-4b77-9ce1-6a0a015838ba",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "82830932-1f16-4e46-a3ab-0b8e6737cf4c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8158a447-e61e-42b5-be60-8ef828c00d72",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "34596703-cdb8-4886-94a4-5e91d97bd5cb",
                "ordinal": 3
              }
            ],
            "lineageTag": "476e49f1-b190-4c63-b42e-b5f5967f60cb"
          }
        ],
        "isHidden": true,
        "lineageTag": "b6e53eba-1cb1-4c1b-85f4-6f1bad40818c",
        "partitions": [
          {
            "name": "LocalDateTable_dc08e2f9-2e5d-4293-aebb-3f213209a326",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ClFacture'[Datdel])), 1, 1), Date(Year(MAX('ClFacture'[Datdel])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e2f21bfc-d774-4e2b-84d2-cd41e8fad56f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "10d85d98-1274-4406-ba65-08810a74ad85",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7152e44c-43cb-41ec-8d22-132100967a72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c90c36fc-b026-44a5-b7b1-b311ae62001e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "98788b6f-4472-4026-943e-44286cfca0b1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "85a8af70-6ad5-464b-8828-aa546cec81ea",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cfab39b9-35d8-4b47-bd8b-b4cc3707f6f5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8686aa33-2c50-4f9a-ba8f-db9a958f3038",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f9f7d17d-d84d-49ef-b72c-04cd705764e2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d6ed8b4f-ea0f-4287-bd61-619170b4e79d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d32b0a14-a42a-4917-8724-e6cc25c90a2b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1eddcdcd-1858-4341-854e-60f5f517858d",
                "ordinal": 3
              }
            ],
            "lineageTag": "dec34f0e-c0d5-4345-ae22-4a943af8942d"
          }
        ],
        "isHidden": true,
        "lineageTag": "b41c3958-e237-4584-92b0-09bfed4c7ecd",
        "partitions": [
          {
            "name": "LocalDateTable_e2f21bfc-d774-4e2b-84d2-cd41e8fad56f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ClFacture'[Date_Remise])), 1, 1), Date(Year(MAX('ClFacture'[Date_Remise])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e39e7027-7cab-4869-99f4-0ec0692a857b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a028ed8b-62dd-405b-82c4-27d342dec620",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2f90e0f5-0e52-4b2b-8277-d1e87f3c47ab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "27be56a6-c3e1-445a-a6f7-1af01205e638",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2d3b53b2-b1da-44b7-a2db-e87246e2b7d0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "229ed05e-d5f7-4679-a7ad-51449aa10009",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "43e9a48b-1ac5-44c3-a86f-f06bc2296c6d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9f41de59-dfd8-4084-bb6a-aef4bcc8558e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d8ff79a4-a855-41ad-8093-c2c392338736",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "459db0d6-059b-4b7e-810d-7be2cb53fa2f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "57a2989d-1096-4b11-a807-7f11af3be311",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "db14bf8c-614b-4558-8794-52b735c9b864",
                "ordinal": 3
              }
            ],
            "lineageTag": "50f3b45d-f65b-4934-81e2-7652618b0e68"
          }
        ],
        "isHidden": true,
        "lineageTag": "af5afa46-41ea-426c-a3fd-8b3e3bd12a58",
        "partitions": [
          {
            "name": "LocalDateTable_e39e7027-7cab-4869-99f4-0ec0692a857b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ClFacture'[date_valider_ho])), 1, 1), Date(Year(MAX('ClFacture'[date_valider_ho])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Mesure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b165fdd-90fc-480b-982c-9dfa00610a01",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fcf35fcc-5560-4f32-a6d8-ea77df4a2854",
        "measures": [
          {
            "name": "titre_CHP_mois",
            "expression": "\"Masses salariales mensuelles \" & CONVERT([MaxXYear] ,string)",
            "lineageTag": "e26f5b1b-2e87-47eb-8741-705386337a0f"
          },
          {
            "name": "titre_contribution",
            "expression": "\"CA / effectif moyen \" & CONVERT([MaxXYear],string)",
            "lineageTag": "f87e7ae9-fc86-4dab-a495-8f347f7fb132"
          },
          {
            "name": "titre effectif",
            "expression": "\"Effectif moyen par service en \"& CONVERT([MaxXYear],string)",
            "lineageTag": "a438689a-0c16-42ac-8003-10494e40a0a2"
          },
          {
            "name": "titre_salaire_mois",
            "expression": "\"Evolution des masses salariales mensuels\" & \" par mois\"",
            "lineageTag": "3bbe1f64-301e-436f-aa3e-10a5da2ac4bf"
          },
          {
            "name": "titre_ca_mois",
            "expression": "\"%Ratio Chiffres d'affaires par mois\"",
            "lineageTag": "8b443fac-e7cd-44bc-bdde-ae92d4121fb1"
          }
        ],
        "partitions": [
          {
            "name": "Mesure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "service_paie",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "19f07e9788a443fbb1c9bfbbef264fea"
          }
        ],
        "columns": [
          {
            "name": "service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6f3b0051-16b5-454f-bec2-3d36df3724aa",
            "sourceColumn": "reporting salaire[service]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "matser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0c037186-662f-4fad-9cb7-9bcd27ffc0d3",
            "sourceColumn": "reporting salaire[matser]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Clinique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "23280df1-a437-4d4c-8c55-e3e6d8393dd2",
            "sourceColumn": "reporting salaire[Clinique]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c29160df-58ef-466b-886e-22a359204c92",
        "partitions": [
          {
            "name": "service_paie",
            "mode": "import",
            "source": {
              "expression": [
                "DISTINCT (summarize ( FILTER (",
                "        'reporting salaire',  -- Table principale à agréger",
                "        NOT ISBLANK('reporting salaire'[matser])  -- Exclure les valeurs null de la colonne 'matser'",
                "    ),'reporting salaire'[service],'reporting salaire'[matser],'reporting salaire'[Clinique]  ))"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9a7f01e8-a7fa-4689-91b2-feb5608b4ba7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "72bfaea2-f485-4960-ab08-89545232c728",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "517f7f89-473e-4d1d-b208-90dc7e416b39",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c6758820-66b1-4921-b117-855891f9e364",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9e063ebf-efde-4fdd-8405-524321673262",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5c646e5b-1148-4c41-a857-e9d399ad1b0a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5310ed80-4fe3-408e-8541-eacac5096afc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8be6d06b-779d-405b-a6bd-c84e21b13f2c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3eb5c034-9e4e-45c3-92a2-d28fd75981ce",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5eec84cc-59bb-4cfe-ba1e-c28c8fcee1f3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "34e46efa-36bf-4e65-b304-79fbc6684e65",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "57a1c6d3-8463-460b-91f7-7c29347ff069",
                "ordinal": 3
              }
            ],
            "lineageTag": "aa1b995a-53de-4ae2-96ca-f6e8feebea3c"
          }
        ],
        "isHidden": true,
        "lineageTag": "37666c62-2cb6-4e7d-9ec3-ad2d1d6b3f5e",
        "partitions": [
          {
            "name": "LocalDateTable_9a7f01e8-a7fa-4689-91b2-feb5608b4ba7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dates'[Date])), 1, 1), Date(Year(MAX('Dates'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}